opeimize: use fileListener singleton
seata/seata pull request #3222
Opened 2020-10-26 10:15 UTC by caohdgege

### Ⅰ. Describe what this PR did
由原来的每个dataId, configurationListener对应一个FileListener的死循环
改成所有的FileListener就对应一个死循环

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-10-26 10:18 UTC, a364176773 requested changes

2020-10-26 10:18 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
>          fileListener.onProcessEvent(new ConfigurationChangeEvent());
既然是一个实例了，没有必要去不断的new ConfigurationChangeEvent了吧？

2020-10-26 10:18 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
>          public void onChangeEvent(ConfigurationChangeEvent event) {
应该在下面根据不同的dataid去构建对应的event实例，而不是就用同一个了

2020-10-26 10:40 UTC, caohdgege commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
>          public void onChangeEvent(ConfigurationChangeEvent event) {
用同一个实例其实也行，因为这一段在执行的时候是串行的

2020-10-26 12:07 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
>          public void onChangeEvent(ConfigurationChangeEvent event) {
确认了下,是的,因为串行执行,会覆盖掉内部的dataid,那么应该改动下避免new多个ConfigurationChangeEvent就好了

2020-10-27 06:06 UTC, a364176773 requested changes

2020-10-27 06:06 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +            Set<ConfigurationChangeListener> changeListeners = dataIdMap.getOrDefault(dataId, new HashSet<>());
dataIdMap .computeIfAbsent(dataId,value->new HashSet<>())

2020-10-27 06:06 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +        private final Map<String, Set<ConfigurationChangeListener>> dataIdMap = new HashMap<>();
Is there a thread safety issue?

2020-10-27 07:37 UTC, caohdgege commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +            Set<ConfigurationChangeListener> changeListeners = dataIdMap.getOrDefault(dataId, new HashSet<>());
ok

2020-10-27 07:41 UTC, caohdgege commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +        private final Map<String, Set<ConfigurationChangeListener>> dataIdMap = new HashMap<>();
modify to use concurrent safe map & set

2020-10-27 09:34 UTC, a364176773 approved these changes
LGTM

2020-10-28 03:22 UTC, slievrly commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +        fileListener.onProcessEvent(new ConfigurationChangeEvent());
Why not start onProcessEvent the first time you add a listener？

2020-10-28 03:57 UTC, slievrly approved these changes
LGTM

2020-10-28 03:58 UTC, merged