change client.log.exceptionRate to log.exceptionRate
seata/seata pull request #3247
Opened 2020-11-01 09:17 UTC by ls9527

### Ⅰ. Describe what this PR did
StackTraceLogger 打印的debug,info,error 日志会根据配置 client.log.exceptionRate 随机打印错误栈。
事实上info 日志在 rm, warn日志在tm, error 日志在tc.  所以 client 的前缀就不准确。 希望去掉client前缀

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-02 02:36 UTC, a364176773 approved these changes
LGTM, use optimize: as the heading prefix

2020-11-06 06:36 UTC, caohdgege requested changes
plz change LogProperties, otherwise seata could not read config from yml
&& plz change application.properties, config.txt, application.yml

需要修改一下LogProperties这个类，不然的话seata是没办法从yml(properties)文件读取配置，
同时需要把application.properties, config.txt, application.yml里面的配置项也对应修改一下

2020-11-07 07:41 UTC, a364176773 commented on seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
>        "sourceType": "io.seata.spring.boot.autoconfigure.properties.client.LogProperties",
+1

2020-11-07 07:42 UTC, a364176773 commented on script/client/conf/file.conf
>      exceptionRate = 100
+1

2020-11-07 13:50 UTC, ls9527 commented on script/client/conf/file.conf
>      exceptionRate = 100
缩进改了，  idea 的默认对其他类型的配置文件是4个空格的缩进。
可以通过加入 .editorconfig 配置文件， 对java,properties,yml.conf 等后缀的缩进排版统一。  
如果这种事情发生的比较多， 就可以考虑一下。  
反正idea能直接导出.editorconfig 文件， 在做一点点修改就可以了

2020-11-07 13:51 UTC, ls9527 commented on seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
>        "sourceType": "io.seata.spring.boot.autoconfigure.properties.client.LogProperties",
已改

2020-11-22 12:30 UTC, caohdgege reviewed
LGMT, 顺便去官网提交一下pr修改一下对应的配置项

2020-11-22 12:30 UTC, caohdgege approved these changes
LGMT, 顺便去官网提交一下pr修改一下对应的配置项

2020-11-23 01:36 UTC, l81893521 approved these changes
LGTM

2020-11-23 01:36 UTC, merged