optimize: refactor loadBalance config from registry.conf to file.conf.
seata/seata pull request #3248
Opened 2020-11-01 11:14 UTC by ls9527

### Ⅰ. Describe what this PR did
loadbalance的配置在 registry.conf 文件， 这个文件属于配置中心的基础配置， 除了指定方式和基础信息以外，其他信息不应该在这个文件。 把loadBalance改到核心配置文件中(file.conf).  

例如随机负载均衡
loadBalance = {
    type = "RandomLoadBalance"
}

还有一致性hash负载均衡
loadBalance = {
    type = "ConsistentHashLoadBalance"
    visualNodes=10
}

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-01 16:29 UTC, caohdgege commented
[ERROR] /home/travis/build/seata/seata/seata-spring-boot-starter/src/test/java/io/seata/spring/boot/autoconfigure/PropertiesTest.java:[223,59] cannot find symbol
  symbol:   class LoadBalanceProperties
  location: class io.seata.spring.boot.autoconfigure.PropertiesTest
[ERROR] /home/travis/build/seata/seata/seata-spring-boot-starter/src/test/java/io/seata/spring/boot/autoconfigure/PropertiesTest.java:[224,42] cannot find symbol
  symbol:   class LoadBalanceProperties
  location: class io.seata.spring.boot.autoconfigure.PropertiesTest

2020-11-01 16:29 UTC, caohdgege commented
处理一下ci的报错

2020-11-02 02:42 UTC, a364176773 requested changes
In addition, please in server/file. Conf. Example, script/server/conf and client/conf&spring, add configuration information

2020-11-02 02:42 UTC, a364176773 commented on seata-spring-boot-starter/src/test/java/io/seata/spring/boot/autoconfigure/PropertiesTest.java
> +import io.seata.spring.boot.autoconfigure.properties.registry.*;
* is not allowed

2020-11-02 02:42 UTC, a364176773 commented on server/src/main/resources/registry.conf
> +
Blank lines can be removed

2020-11-02 02:51 UTC, a364176773 commented
@ph3636 PTAL

2020-11-02 12:59 UTC, ph3636 commented
Search it according to the keyword (loadBalanceVirtualNodes), or check it through git records, there are still many places that have not been changed.
根据关键词（loadBalanceVirtualNodes）搜一下，或者通过git记录看下，还有好多地方没改。

2020-11-02 13:13 UTC, ls9527 commented
@ph3636  好的，  修改了。 
@caohdgege 已经提交了遗漏提交的文件

2020-11-03 03:28 UTC, ph3636 commented
I think this configuration is more appropriate to put in the client, the server will not use this configuration
我觉得这个配置放到client中比较合适，server不会用到这个配置

2020-11-03 04:21 UTC, ls9527 commented
> I think this configuration is more appropriate to put in the client, the server will not use this configuration
> 我觉得这个配置放到client中比较合适，server不会用到这个配置

有道理阿， 只有TM，RM才需要负载均衡。  TC都知道发给谁了，就不用均衡了。   那我在改改

2020-11-04 04:44 UTC, ph3636 commented
Change these files
改一下这些文件
script/client/spring/application.properties
script/client/spring/application.yml
META-INF/additional-spring-configuration-metadata.json

No configuration in these files
下面这些文件中可以不加配置
script/server/config

2020-11-05 05:48 UTC, ph3636 commented on discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/ConsistentHashLoadBalance.java
> +     * The constant LOAD_BALANCE_TYPE.
Change this name
改一下这个名字

2020-11-05 05:48 UTC, ph3636 commented on script/server/config/file.properties
> +loadBalance.consistentHash.virtualNodes=10
These are redundant
这些是多余

2020-11-05 05:48 UTC, ph3636 commented on script/server/config/file.yml
> +    virtualNodes: 10
These are redundant
这些是多余

2020-11-05 13:45 UTC, ls9527 commented on script/server/config/file.yml
> +    virtualNodes: 10
多谢大神， 已将多余的部分删除。  将loadBalance的 type 和  visualNodes 区分开了。

2020-11-06 06:51 UTC, ph3636 approved these changes
LGTM

2020-11-06 06:51 UTC, ph3636 commented on discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/ConsistentHashLoadBalance.java
> +     * The constant LOAD_BALANCE_TYPE.
Change the name or delete it

2020-11-22 12:39 UTC, a364176773 commented on discovery/seata-discovery-core/src/test/resources/file.conf
> +#
unwanted file

2020-11-22 12:43 UTC, a364176773 requested changes

2020-11-22 12:43 UTC, a364176773 commented on script/server/config/file.conf
> +}
unnecessary change

2020-11-22 12:43 UTC, a364176773 commented on script/server/config/file.properties
> +store.redis.queryLimit=100
unnecessary change

2020-11-22 12:43 UTC, a364176773 commented on script/server/config/file.yml
> +    queryLimit: 100
unnecessary change

2020-11-22 12:43 UTC, a364176773 commented on server/src/main/resources/file.conf
> +}
unnecessary change

2020-11-22 12:45 UTC, ls9527 commented on discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/ConsistentHashLoadBalance.java
> +     * The constant LOAD_BALANCE_TYPE.
一直以为改了，今天核对才发现没改。  刚刚改掉了

2020-11-22 12:48 UTC, ls9527 commented on script/server/config/file.properties
> +loadBalance.consistentHash.virtualNodes=10
多余的删掉了

2020-11-25 10:30 UTC, a364176773 commented
请解决代码冲突

2021-01-17 09:37 UTC, a364176773 approved these changes
LGTM

2021-02-18 02:23 UTC, l81893521 commented on changes/en-us/1.5.0.md
> +  - [[#3248](https://github.com/seata/seata/pull/3248)] optimize the config of load-balance migration to belong the client node
migrate instead of migration, migration is not a verb.

2021-02-18 03:27 UTC, l81893521 approved these changes
LGTM

2021-03-19 02:48 UTC, xingfudeshi approved these changes
LGTM.

2021-03-19 02:48 UTC, merged

2023-01-05 02:42 UTC, wangliang181230 commented on discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/ConsistentHashLoadBalance.java
> +    public static final String LOAD_BALANCE_CONSISTENT_HASH_VISUAL_NODES = LOAD_BALANCE_PREFIX + "visualNodes";
@xingfudeshi 
配置名 `visualNodes` 与 `LoadBalanceProperties` 类里的field `virtualNodes` 名不一致，导致在 `SpringBootConfigurationProvider` 下，获取字段时不存在，导致返回为null。
也就是说在springboot下，配置了`seata.client.load-balance.visual-nodes` 或 `seata.client.load-balance.virtual-nodes`都会导致配置读取不到。