bugfix: fix wrong status when exception
seata/seata pull request #3281
Opened 2020-11-13 09:03 UTC by anselleeyy

### Ⅰ. Describe what this PR did

fix wrong status when some exception
saga 分支事务启动时，如遇异常，导致上报分支事务状态为：rollbacked，无法继续重试

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-17 03:45 UTC, long187 commented
@anselleeyy 这个问题，当时是这样设计的，在`io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor#preProcess` 方法实际上是还没有执行这个服务，所以发生异常，不会把这个服务的执行结果放到整体事务状态的判断里，所以当第一个服务执行就因为写state_inst表失败了，则整体事务是没有执行过任何服务，所以是FA，不会由server进行重试，而是需要业务上重新发起一笔新交易。

2020-11-26 07:50 UTC, long187 requested changes
建议把setMachineStatusBasedOnException的代码直接合到setMachineStatusBasedOnStateList里，方法名称可以改成setMachineStatusBasedOnStateListAndException，这样就不用遍历两次stateList了。

2020-11-26 08:07 UTC, long187 commented
@anselleeyy

2020-11-26 09:15 UTC, anselleeyy commented
@long187 好的。。已按建议调整~ 

这里调整了一下 `setMachineStatusBasedOnException` ，在解析 exp 之前如果存在更新类服务就直接返回 UN 了，而不去判断是何种类型的网络问题，辛苦看下这样是否可行呢。。

2020-11-26 11:47 UTC, long187 commented
@anselleeyy OK可以，[大拇指]

2020-11-26 11:47 UTC, long187 approved these changes
LGTM

2020-11-27 06:32 UTC, long187 commented
@anselleeyy 你在钉钉群吗？钉钉号是什么，以后多交流

2020-11-27 06:37 UTC, anselleeyy commented
@long187 在的，钉钉号：rff0w3x

2020-12-08 05:22 UTC, wangliang181230 approved these changes
LGTM

2020-12-08 05:39 UTC, merged