bugfix:update pk throw exception
seata/seata pull request #3287
Opened 2020-11-16 09:52 UTC by 81519434

### Ⅰ. Describe what this PR did
optimize this pr. #3129

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-17 02:53 UTC, a364176773 requested changes
please use p3C to format the code

2020-11-17 02:53 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java
> +import java.sql.SQLException;
java packages should be at the top

2020-11-19 16:00 UTC, caohdgege commented
关联一下#3289

2020-11-20 03:54 UTC, 81519434 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java
> +import java.sql.SQLException;
done

2020-11-27 07:12 UTC, xingfudeshi commented
This problem is that the primary key should not be changed. If the new primary key value is consistent with the old primary key value, can it be ignored directly?@81519434

2020-11-30 08:52 UTC, 81519434 commented
> This problem is that the primary key should not be changed. If the new primary key value is consistent with the old primary key value, can it be ignored directly?@81519434

Yes, this pr is doing exactly what you said!

2020-11-30 12:53 UTC, xingfudeshi approved these changes
LGTM.

2020-12-08 04:30 UTC, slievrly approved these changes
LGTM

2020-12-08 04:57 UTC, a364176773 approved these changes
LGTM

2020-12-08 05:33 UTC, merged