feature:Support to obtain multiple configurations through a single dataid in Nacos
seata/seata pull request #3303
Opened 2020-11-24 04:22 UTC by Rubbernecker

### Ⅰ. Describe what this PR did
添加从nacos单一dataId获取多条配置功能，registry.conf文件添加config.nacos.dataId属性用于指定nacos中的dataId。

### Ⅱ. Does this pull request fix one issue?

#2506 #2316

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
此功能在原有功能上修改，不方便写测试用例。

### Ⅳ. Describe how to verify it
其他功能正常配置后，在registry.conf文件中将config.type设置为“nacos”，添加config.nacos.dataId属性，属性值为nacos中的dataId，例如“seata.properties”，启动seata应用（server或client都可以），会自动拉取nacos上“seata.properties”中的配置。

应用中的配置如下，根据项目选择对应的配置方式：

### application.yml
![image](https://user-images.githubusercontent.com/62733397/100048193-3f0c5900-2e4f-11eb-95cf-d4ee74dde9f3.png)

### registry.conf
![image](https://user-images.githubusercontent.com/62733397/100048215-50edfc00-2e4f-11eb-8fe3-b51fd1cf74df.png)

nacos中的属性配置如下：
![image](https://user-images.githubusercontent.com/62733397/100048296-7418ab80-2e4f-11eb-85c8-0e9bb880d420.png)

### Ⅴ. Special notes for reviews
将config.type设置为“nacos”。
此功能已实现动态配置，同时兼容旧的配置方式。

2020-11-24 04:24 UTC, Rubbernecker commented
a364176773 nacos配置中心的功能已经改好了，之前那个没有实现动态配置，这次加上了，你们看一下。

2020-11-24 09:18 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +            result = configService.publishConfig(getNacosDataId(), getNacosGroup(), getSeataConfigStr());
should it be kept configService.removeConfig(dataId, getNacosGroup());？

2020-11-24 09:18 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +            result = configService.publishConfig(getNacosDataId(), getNacosGroup(), getSeataConfigStr());
should it be kept configService.publishConfig(dataId, getNacosGroup(), content);？

2020-11-24 09:18 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +    private static ConcurrentMap<String, ConcurrentMap<ConfigurationChangeListener, NacosListener>> configListenersMap
It's a singleton

2020-11-24 09:24 UTC, Rubbernecker commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +            result = configService.publishConfig(getNacosDataId(), getNacosGroup(), getSeataConfigStr());
我调的不是remove方法，是publishConfig方法，是把删除的配置同步到nacos上，后面的getSeataConfigStr()是获取所有配置字符串的方法。

2020-11-24 09:24 UTC, Rubbernecker commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +            result = configService.publishConfig(getNacosDataId(), getNacosGroup(), getSeataConfigStr());
同上

2020-11-24 09:27 UTC, Rubbernecker commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +    private static ConcurrentMap<String, ConcurrentMap<ConfigurationChangeListener, NacosListener>> configListenersMap
这是为了让下面的监听器的内部类调用，不然传值太麻烦了

2020-11-24 11:38 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +    private static ConcurrentMap<String, ConcurrentMap<ConfigurationChangeListener, NacosListener>> configListenersMap
那就static final 修饰一下

2020-11-25 02:42 UTC, Rubbernecker commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +    private static ConcurrentMap<String, ConcurrentMap<ConfigurationChangeListener, NacosListener>> configListenersMap
改好了

2020-11-30 14:59 UTC, a364176773 requested changes

2020-11-30 14:59 UTC, a364176773 commented on seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
> +    private String dataId = "";
dataId="seataServer.properties"

2020-11-30 15:01 UTC, Rubbernecker commented on seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
> +    private String dataId = "";
已经加到后面提的pr上了

2020-12-10 07:44 UTC, a364176773 approved these changes
LGTM

2020-12-24 10:51 UTC, l81893521 reviewed
Please record to /changes .md

2020-12-24 10:54 UTC, l81893521 commented on seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
> +    private String dataId = "seata.properties";
Can you keep it same?
```
seata.properties
```
or
```
seataServer.properties
```

2020-12-24 10:57 UTC, Rubbernecker commented on seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
> +    private String dataId = "seata.properties";
默认值都是seata.properties

2020-12-25 04:41 UTC, l81893521 approved these changes
LGTM

2020-12-25 04:50 UTC, merged

2022-04-30 08:12 UTC, liquehuo commented
大佬们，辛苦了！
关于项目里的registry.conf文件中nacos的连接地址问题。
本地开发和线上部署nacos地址是不一样的，怎么样配置比较方便灵活呢？

我现在是本地开发用127.0.0.1:8848
测试服务器上用docker部署，然后nacos地址是：nacos:8848
然后就需要发布的之前就要把 127.0.0.1 改成 nacos ，发布后本地调试又要改回来，这样感觉比较麻烦。

请问下是不是有其他方法或者我哪里姿势不对吗？

2022-05-19 03:00 UTC, raojun0504 commented
seataServer.properties can be replaced by seataServer.yaml ?