optimize: show warning if config file not found
seata/seata pull request #3341
Opened 2020-12-06 07:37 UTC by hoverruan

### Ⅰ. Describe what this PR did

当外部配置文件路径没有以 `file:` 开头而导致的没有加载配置信息时，在日志中给出告警信息，加快排查问题的速度

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

在 registry.conf 文件中配置文件路径的时候，不添加 `file:` 前缀。例如：

```
config {
  type = "file"

  file {
    name = "/root/seata-config/file.conf"
  }
}
```

期望的结果：

1. 配置文件没有被加载
2. 日志中会出现一个警告信息：

```
The configuration file not found: /root/seata-config/file.conf. If your file is on the file system,
please use a format like "file:/path/to/file.conf"
```

### Ⅴ. Special notes for reviews

2020-12-06 08:32 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +        String basename = StringUtils.isNullOrEmpty(name) ? "my-config.conf" : new File(name).getName();
SEATA_CONFIG_NAME是只针对registry.conf的,而file.conf是通过registry中的config.file.name来指定的,建议再ConfigurationFactory#load中做提示输出

2020-12-06 13:59 UTC, xingfudeshi commented
If the prefix is missing, why not complete it automatically?

2020-12-08 12:46 UTC, a364176773 requested changes

2020-12-08 13:19 UTC, hoverruan commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +        /*
/** 开头是 javadoc 的语法，方法内的注释应该用 /* 开头

2020-12-08 13:20 UTC, hoverruan commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +            LOGGER.error("file not found--" + e.getMessage(), e);
这是原来的代码，重构的时候没有改动

2020-12-09 03:33 UTC, xingfudeshi commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +            LOGGER.error("decode name error", e);
LOGGER.error("decode name error:{}",e.getMessage(), e);

2020-12-09 03:34 UTC, xingfudeshi commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +            path = URLDecoder.decode(path, "utf-8");
URLDecoder.decode(path, StandardCharsets.UTF_8);

2020-12-09 03:34 UTC, xingfudeshi commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
>                      path = URLDecoder.decode(path, "utf-8");
URLDecoder.decode(path, StandardCharsets.UTF_8);

2020-12-12 11:55 UTC, xingfudeshi approved these changes
LGTM.

2020-12-12 11:56 UTC, xingfudeshi commented
@a364176773

2020-12-13 05:57 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
> +            // 是否指定文件系统上的路径
建议使用英文注释

2020-12-19 15:45 UTC, a364176773 approved these changes
LGTM

2020-12-21 02:43 UTC, merged