feature: Saga support customize if persist retry and compensate execution log
seata/seata pull request #3372
Opened 2020-12-14 07:44 UTC by anselleeyy

### Ⅰ. Describe what this PR did

support customize if persist retry and compensate execution log
支持自定义saga状态机，是否持久化记录 重复重试和补偿的中间状态过程，默认记录

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-12-17 03:20 UTC, long187 requested changes

2020-12-17 03:20 UTC, long187 commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
> +            boolean isPersist = true;
这个变量叫 isUpdateMode = false; 是不是更合适，因为并不是不persist

2020-12-17 03:20 UTC, long187 commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
> +                if (compensateStateInstanceId.endsWith("-1") || !isUpdateMode(stateInstance, context)) {
这里用id是不是-1结尾判断可能容易留坑，如果id生成规则变了。建议是用tateIdCompensatedFor找到原stateInstace，然后stateInstace.getCompensationState()来取它上一次的补偿服务的id

2020-12-17 13:09 UTC, anselleeyy commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
> +            boolean isPersist = true;
fixed

2020-12-17 13:13 UTC, anselleeyy commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
> +                if (compensateStateInstanceId.endsWith("-1") || !isUpdateMode(stateInstance, context)) {
这里 originInst 的 compensationState 会被set成当前的 [stateInst](https://github.com/seata/seata/blob/607571689abfb3de74971d14d4f4ca7f908d1861/saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/interceptors/ServiceTaskHandlerInterceptor.java#L149)，无法获取到上一次补偿 inst 的id，这里判断做了下调整，辛苦 review 下是否可行~

2020-12-21 12:20 UTC, long187 requested changes

2020-12-21 12:20 UTC, long187 commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
> +                if (isUpdateMode) {
此处简化成：stateInstance.setId(generateCompensateStateInstanceId(stateInstance, isUpdateMode)); 即可

2020-12-22 02:21 UTC, long187 approved these changes
LGTM

2020-12-22 03:00 UTC, wangliang181230 commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/StateLogStoreSqls.java
> +        = "UPDATE ${TABLE_PREFIX}state_inst SET status = ?, gmt_started = ? WHERE machine_inst_id = ? AND id = ?";
我认为还是添加一个`gmt_updated`字段比较好吧。

2020-12-22 05:33 UTC, anselleeyy commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/StateLogStoreSqls.java
> +        = "UPDATE ${TABLE_PREFIX}state_inst SET status = ?, gmt_started = ? WHERE machine_inst_id = ? AND id = ?";
fixed

2020-12-22 06:13 UTC, long187 requested changes

2020-12-22 06:13 UTC, long187 commented on script/client/saga/db/mysql.sql
> +    `gmt_updated`              DATETIME(3) NOT NULL COMMENT 'update time',
gmt_updated最好是允许null吧，因为数据库加了字段后，应用还没有升级，老的代码不会更新这个字段，这时SQL可能会报错。

2020-12-22 06:55 UTC, anselleeyy commented on script/client/saga/db/mysql.sql
> +    `gmt_updated`              DATETIME(3) NOT NULL COMMENT 'update time',
fixed

2020-12-22 07:00 UTC, long187 approved these changes
LGTM

2020-12-22 09:02 UTC, wangliang181230 commented on saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/impl/StateMachineImpl.java
> +    public boolean isCompensatePersistModeUpdate() {
`@Override`

2020-12-22 09:02 UTC, wangliang181230 commented on saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/impl/StateMachineImpl.java
> +    public boolean isRetryPersistModeUpdate() {
`@Override`

2020-12-22 09:06 UTC, wangliang181230 commented on seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "name": "seata.client.rm.saga-retry-persist-mode-update",
`Boolean`不需要添加`hints`，默认值已经显示在提示语中了的。
例：
![图片](https://user-images.githubusercontent.com/1527893/102870489-0bd1df80-4478-11eb-9923-69ed85a941ce.png)

2020-12-22 09:07 UTC, wangliang181230 commented on seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "defaultValue": "false"
`false`不需要双引号。
下同。

2020-12-22 09:14 UTC, wangliang181230 commented on saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/StateMachine.java
> +    boolean isRetryPersistModeUpdate();
我认为这两个配置项的值应改为Boolean。

2020-12-22 09:14 UTC, wangliang181230 commented on saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/ServiceTaskState.java
> +    boolean isRetryPersistModeUpdate();
我认为这两个配置项的值应改为Boolean。

2020-12-22 09:17 UTC, wangliang181230 commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
> +                .getStateMachine().isRetryPersistModeUpdate() || state.isRetryPersistModeUpdate();
我认为这三处的配置是有优先级的。首先StateMachine和State的两个属性的类型需变更为`Boolean`。
然后优先级是`state > stateMachine > config`。
否则config中配置为true，stateMachine或state中的配置就没有任何意义了不是？

2020-12-22 09:25 UTC, wangliang181230 commented on saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
> +                .getStateMachine().isRetryPersistModeUpdate() || state.isRetryPersistModeUpdate();
```
if (state.isRetryPersistModeUpdate() != null) {
    return state.isRetryPersistModeUpdate();
}
if (stateMachine.isRetryPersistModeUpdate() != null) {
    return stateMachine.isRetryPersistModeUpdate();
}
return config.isSagaRetryPersistModeUpdate();
```

2020-12-24 00:01 UTC, wangliang181230 approved these changes
LGTM

2020-12-24 03:35 UTC, long187 approved these changes
LGTM

2020-12-24 03:36 UTC, merged