bugfix:INSERT ON DUPLICATE KEY UPDATE当update时会抛异常，新加一个Executor
seata/seata pull request #3374
Opened 2020-12-14 12:10 UTC by huan415

### Ⅰ. Describe what this PR did
新加一个Executor, 执行INSERT ON DUPLICATE KEY UPDATE

### Ⅱ. Does this pull request fix one issue?

INSERT ON DUPLICATE KEY UPDATE当update时会抛异常

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it
如果含有ON DUPLICATE KEY UPDATE则走新的执行器，利用唯一索引查前置和后置镜像，如果有前置镜像则包含update，没有前置镜像则为insert

### Ⅴ. Special notes for reviews

2020-12-14 12:47 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
ON DUPLICATE KEY UPDATE It should be set to a constant

2020-12-14 12:48 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
DBType.MYSQL?

2020-12-14 16:54 UTC, caohdgege commented
为什么这个有executor，但是没有对应的undoExecutor的，这样的话，在回滚的场景下是怎么处理的？

2020-12-15 01:32 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
+1

2020-12-22 12:04 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
可以的，谢谢

2020-12-22 12:10 UTC, huan415 commented
> ，



> 为什么这个有executor，但是没有对应的undoExecutor的，这样的话，在回滚的场景下是怎么处理的？

undoExecutor这个逻辑不用动。还是走原来的逻辑。
回滚场景是根据SQLUndoLog的SqlType来判断，这种sql生成的SQLUndoLog可能是insert也可能是update，也有可能两种都有，

2020-12-22 12:11 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
这个是我欠考虑了。没找到能具体一点吗？是MysqlInsertStatement里的duplicateKeyUpdate，这个是有update的字段，您是指这个吗？

2020-12-22 12:58 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
是的，就是这个

2020-12-22 14:50 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                if (!"PRIMARY".equals(k.toUpperCase()) && !v.isNonUnique()) {
这里为什么跳过了主键？主键也具有唯一性，也应该触发这个才对呀？

2020-12-22 14:50 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                    if (suffix.toString().contains("WHERE")) {
这里用contains的性能是不是会差一点？并且contains的话，是不是有可能误判？

2020-12-22 14:54 UTC, caohdgege commented
```java
    @GlobalTransactional(timeoutMills = 3000000)
    public void tcc(@RequestParam(value = "times", required = false, defaultValue = "1") int times,
                    @RequestParam(value = "batchNum", required = false, defaultValue = "100") int batchNum,
                    @RequestParam(value = "thr", required = false, defaultValue = "0") int thr) throws SQLException {
        Connection connection = dataSource.getConnection();
        System.out.println(connection instanceof ConnectionProxy);
        String sql = "insert into user(id, username, PASSWORD, email, phone, sex) values (1, 'fdafdasdfa', 'fdasfas', 'fdafasdd', 'fdasfasdfasdf', ?),  (3002, 'fdafdasdfa', 'fdasfas', 'fdafasdd', 'fdasfasdfasdf', ?) ON DUPLICATE KEY UPDATE username='fdafas'";
        PreparedStatement ps = connection.prepareStatement(sql);
        ps.setInt(1, 0);
        ps.setInt(2, 1);
        ps.executeUpdate();
        ps.executeUpdate();
        if (true) {
            throw new RuntimeException();
        }
    }
```
我数据库里面3002的数据是存在的，id=1的数据是不存在的，username是唯一键，这样测试的话，在回滚的时候会把我id=3002的数据误删除。
附上我user表的建表语句。
```sql
create table if not exists seata_tx_test.user
(
	id bigint unsigned auto_increment
		primary key,
	username varchar(255) not null comment '用户名',
	PASSWORD char(36) not null comment '密码',
	email char(100) not null comment '邮箱',
	phone char(20) not null comment '电话号码',
	logo char(255) default '/default-logo.png' not null comment '头像',
	address char(150) default '' not null comment '地址',
	sex tinyint default 0 not null comment '0->未设置 1->男 2->女',
	constraint email
		unique (email),
	constraint uniq_phone_sex
		unique (phone, sex),
	constraint username
		unique (username)
)
collate=utf8mb4_general_ci;
```

2020-12-22 14:56 UTC, caohdgege commented
把开发分支合并到你的分支再推一下，看一下ci能不能过。

2020-12-22 15:21 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
已改正，望采纳

2020-12-23 02:13 UTC, caohdgege commented
我觉得这个应该算是特性 feature，之前不支持 ON DUPLICATE KEY UPDATE，这个pr就是让seata支持这种语法。
还有标题稍微改一下，pr的标题不要用中文。

2020-12-23 02:26 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        if(sqlRecognizer.getOriginalSQL().toUpperCase().trim().contains("ON DUPLICATE KEY UPDATE".trim()) && "mysql".equals(dbType)){
改完了就可以自己点一下Resolve conversation。

2020-12-24 02:39 UTC, huan415 commented on sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/SQLInsertRecognizer.java
> +    List<String> getInsertParamsValue();
这个不是sql, 主要下想获取占位符，通过占位符来获取各个字段对应的值，之所以考虑有占位符来获取对应的字段值，是考虑values有可能是常量，比如说nows().   如果有常量时,statementProxy.getParameters与recognizer.getInsertColumns无法一 一对应

2020-12-24 02:43 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                if (!"PRIMARY".equals(k.toUpperCase()) && !v.isNonUnique()) {
这个是因为前置镜像获取不到id，而我那时候的业务场景如果id一样，唯一索引也是一样的，所以过滤掉的。从理论上说是不应该去掉，我再想想办法

2020-12-24 02:46 UTC, huan415 commented
> ```java
>     @GlobalTransactional(timeoutMills = 3000000)
>     public void tcc(@RequestParam(value = "times", required = false, defaultValue = "1") int times,
>                     @RequestParam(value = "batchNum", required = false, defaultValue = "100") int batchNum,
>                     @RequestParam(value = "thr", required = false, defaultValue = "0") int thr) throws SQLException {
>         Connection connection = dataSource.getConnection();
>         System.out.println(connection instanceof ConnectionProxy);
>         String sql = "insert into user(id, username, PASSWORD, email, phone, sex) values (1, 'fdafdasdfa', 'fdasfas', 'fdafasdd', 'fdasfasdfasdf', ?),  (3002, 'fdafdasdfa', 'fdasfas', 'fdafasdd', 'fdasfasdfasdf', ?) ON DUPLICATE KEY UPDATE username='fdafas'";
>         PreparedStatement ps = connection.prepareStatement(sql);
>         ps.setInt(1, 0);
>         ps.setInt(2, 1);
>         ps.executeUpdate();
>         ps.executeUpdate();
>         if (true) {
>             throw new RuntimeException();
>         }
>     }
> ```
> 
> 我数据库里面3002的数据是存在的，id=1的数据是不存在的，username是唯一键，这样测试的话，在回滚的时候会把我id=3002的数据误删除。
> 附上我user表的建表语句。
> 
> ```sql
> create table if not exists seata_tx_test.user
> (
> 	id bigint unsigned auto_increment
> 		primary key,
> 	username varchar(255) not null comment '用户名',
> 	PASSWORD char(36) not null comment '密码',
> 	email char(100) not null comment '邮箱',
> 	phone char(20) not null comment '电话号码',
> 	logo char(255) default '/default-logo.png' not null comment '头像',
> 	address char(150) default '' not null comment '地址',
> 	sex tinyint default 0 not null comment '0->未设置 1->男 2->女',
> 	constraint email
> 		unique (email),
> 	constraint uniq_phone_sex
> 		unique (phone, sex),
> 	constraint username
> 		unique (username)
> )
> collate=utf8mb4_general_ci;
> ```

刚刚试了一下，用mybatis不会。这个是因为单引号的问题（SELECT *  FROM user WHERE (email = ' \'fdafasdd\'' )  OR (phone = ' \'fdasfasdfasdf\''  and sex = 0 )  OR (username = ' \'fdafdasdfa\'' )  OR (email = ' \'fdafasdd\'' )  OR (phone = ' \'fdasfasdfasdf\''  and sex = 1 )  OR (username = ' \'fdafdasdfa\'' )  FOR UPDATE），  所以认为获取不到前置镜像，认为两条都是insert，回滚时都删掉。 这是个bug，我想想

2020-12-24 02:46 UTC, huan415 commented
> feature

ok

2020-12-26 10:19 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                if (!"PRIMARY".equals(k.toUpperCase()) && !v.isNonUnique()) {
已改正，如果insert前置镜像没有id，则不列入查询条件

2020-12-26 10:22 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                    if (suffix.toString().contains("WHERE")) {
这个sql是我们自己拼接来查询镜像，一般不会有误判。
改为声明了一个flag，第一次的时候拼接where，以后拼接的是or

2020-12-26 11:51 UTC, huan415 commented
> 把开发分支合并到你的分支再推一下，看一下ci能不能过。

合并了一下主线代码，checks可以通过了

2020-12-27 16:07 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +import java.util.Map;
java开头的import要调到上面。

2020-12-27 16:07 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +    //is updated or not
用以下的注释方式
/**
 * 
 */

2020-12-27 16:07 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +    protected void prepareUndoLog2(TableRecords beforeImage, TableRecords afterImage) {
这个方法名能不能优化一下？

2020-12-27 16:12 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +            Boolean[] isUpdateRows = {false};
这里为什么是个数组来的？

2020-12-28 13:51 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +import java.util.Map;
已改，能说一下原因吗

2020-12-28 13:57 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +            Boolean[] isUpdateRows = {false};
这是一个flag, 遍历后置镜像里的每条数据，如果该条数据的唯一索引在前置镜像已经存在，则标记成true。后面根据这个值判断是insertUndolog，还是updateUndolog。
我在外面声明boolean，steam里面不能用，所以用数组。如果用数组不好，我改成AtomicBoolean

2020-12-28 13:58 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +import java.util.Map;
规范吧。。。我进来的时候大佬们跟我说的。。。

2020-12-28 14:19 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +            Boolean[] isUpdateRows = {false};
这里的话，你其实就是需要一个引用类型，然后让他可以在stream里面使用对吧？有没有一些更优雅的使用方式？

2021-01-02 11:45 UTC, huan415 commented
平时没写过测试用例，能给个例子吗

2021-01-07 15:19 UTC, caohdgege commented
MySQLInsertRecognizer.java 的 getSQLType 那个方法的实现要改一下，return isDuplicateKeyUpdate() ? SQLType.INSERT_ON_DUPLICATE_UPDATE : SQLType.INSERT

2021-01-10 05:40 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +        TableRecords lockKeyRecords = sqlRecognizer.getSQLType() == SQLType.DELETE ? beforeImage : afterImage;
这边是可以直接返回afterImage

2021-01-20 08:17 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                ArrayList<Object> imageListTemp = imageParamperterMap.get(m);
imageParamperterMap.computeIfAbsent(m,k->new ArrayList<>())

2021-02-05 12:46 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        }
else throw new NotSupportYetException ?

2021-02-05 12:46 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        //  break;
这里为什么注释掉的？

2021-02-05 12:46 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +        StringBuilder prefix = new StringBuilder("SELECT * ");
这里的查询的字段，是否需要受onlyCareUpdateColumns这个参数的影响？

2021-02-09 13:35 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        }
其他的dbType，我是想先让mysql试试，如果能被你们采纳，我后续也想支持一下其他的

2021-02-09 13:40 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
> +                        //  break;
注释掉的原因是：如果一个很成熟的项目接入seata，有用到ON DUPLICATE KEY UPDATE，但是他们又不知道seata不支持这种sql.  此时如果没有测试到，上生产环境的话会出问题。所以我想按正常的sql执行（没有分布式事务）。所以我把break注释掉，不影响业务，只是分布式事务没有起作用

2021-02-09 14:11 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +        StringBuilder prefix = new StringBuilder("SELECT * ");
好像有点麻烦，我是前置镜像和后置镜像对比，得出是insert或update。做前置镜像的时候还不知道这个是insert或update, 所以所有字段都查了。有什么比较好的建议？

2021-02-09 15:51 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                                everyRowIndex.append(f.getValue());
这里拼接字符串会不会不是很好？像那种(a,b)的联合唯一索引，a=1,b=22 和 a=12,b=2的话，是不是会导致误判？

2021-02-09 15:51 UTC, caohdgege commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                    beforeUniqueIndexMap.put(k.toUpperCase(), indexList);
这一行是否是多余的？

2021-02-09 15:52 UTC, caohdgege commented
还有把seata/seata的develop分支的代码合并你的分支上，补充一下changes文件夹下面的那两个文件

2021-02-10 05:43 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +                                everyRowIndex.append(f.getValue());
这个会误判，我加分隔符把

2021-02-18 08:28 UTC, xingfudeshi commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> + * @author: yangyicong
please remove :

2021-02-18 08:29 UTC, xingfudeshi commented on rm-datasource/src/test/java/io/seata/rm/datasource/exec/MySQLInsertOrUpdateExecutorTest.java
> + * @author: yangyicong
please remove :

2021-02-18 08:29 UTC, xingfudeshi commented on rm-datasource/src/test/java/io/seata/rm/datasource/exec/MySQLInsertOrUpdateExecutorTest.java
> +import static org.mockito.Mockito.*;
Please do not use *.

2021-02-20 03:02 UTC, xingfudeshi approved these changes
LGTM.

2021-02-20 03:30 UTC, xingfudeshi commented
![image](https://user-images.githubusercontent.com/24457941/108582559-1670fe00-736f-11eb-8bfe-8a0d026857bb.png)

2021-02-21 12:32 UTC, caohdgege commented
SQL里面的主键是auto_increment，并且没有主动赋值的时候，执行会报错，可以通过下面的代码复现。

建表SQL
```sql
create table uk (
    id int unsigned not null auto_increment primary key ,
    f1 int unsigned not null unique ,
    f2 int unsigned not null ,
    f3 int unsigned not null ,
    unique (f2, f3)
);
```
Java代码
```java
    @GetMapping("/test3")
    @GlobalTransactional
    public void test3() throws SQLException {
        ConnectionProxy connection = (ConnectionProxy) dataSource.getConnection();

        String sql = "insert into uk(f1, f2, f3) values (?, ?, ?), (?, ?, ?) on duplicate key update f1=?";
        PreparedStatementProxy ps = (PreparedStatementProxy) connection.prepareStatement(sql);

        ps.setInt(1, 1);
        ps.setInt(2, 1);
        ps.setInt(3, 1);
        ps.setInt(4, 1);
        ps.setInt(5, 2);
        ps.setInt(6, 3);
        ps.setInt(7, 5);
        try {
            ps.executeUpdate();
        } finally {
            IOUtil.close(ps);
            IOUtil.close(connection);
        }
    }
```
报错日志：
```log
2021-02-21 20:24:21.280 ERROR 320318 --- [nio-8430-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  OR (f1 = 1 )  OR (f2 = 2  and f3 = 3 )  OR ()  FOR UPDATE' at line 1] with root cause

java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  OR (f1 = 1 )  OR (f2 = 2  and f3 = 3 )  OR ()  FOR UPDATE' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227) ~[druid-1.1.23.jar:1.1.23]
	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.buildTableRecords2(MySQLInsertOrUpdateExecutor.java:287) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.buildImage(MySQLInsertOrUpdateExecutor.java:265) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.beforeImage(MySQLInsertOrUpdateExecutor.java:250) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.executeAutoCommitFalse(MySQLInsertOrUpdateExecutor.java:103) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:140) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:340) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:184) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:139) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:114) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:122) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:54) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at io.seata.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:65) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
	at cn.caohd.txproviderserver.controller.UserController.test3(UserController.java:286) ~[classes/:na]
```

2021-02-21 14:45 UTC, caohdgege commented
建表SQL：
```sql
create table uk (
    id int unsigned not null auto_increment primary key ,
    f1 int unsigned unique ,
    f2 int unsigned ,
    f3 int unsigned ,
    unique (f2, f3)
);
```
Java代码：
```java
    @GetMapping("/test3")
    @GlobalTransactional
    public void test3() throws SQLException {
        ConnectionProxy connection = (ConnectionProxy) dataSource.getConnection();

        String sql = "insert into uk(f1, f2, f3) values (?, ?, ?) on duplicate key update f1=?";
        PreparedStatement ps = connection.prepareStatement(sql);

        ps.setInt(1, 11);
        ps.setNull(2, Types.INTEGER);
        ps.setInt(3, 0);
        ps.setInt(4, 8);
        try {
            ps.executeUpdate();
            if (true) {
                throw new RuntimeException("123");
            }
        } finally {
            IOUtil.close(ps);
            IOUtil.close(connection);
        }
    }
```
数据库当前的数据：
![image](https://user-images.githubusercontent.com/22959373/108628508-5b438480-7496-11eb-8832-944be1deb392.png)
ConnectionContext的数据好像不太正常
![image](https://user-images.githubusercontent.com/22959373/108628534-7ca47080-7496-11eb-945c-298f438df0b5.png)

2021-02-23 05:08 UTC, huan415 commented
> SQL里面的主键是auto_increment，并且没有主动赋值的时候，执行会报错，可以通过下面的代码复现。
> 
> 建表SQL
> 
> ```sql
> create table uk (
>     id int unsigned not null auto_increment primary key ,
>     f1 int unsigned not null unique ,
>     f2 int unsigned not null ,
>     f3 int unsigned not null ,
>     unique (f2, f3)
> );
> ```
> 
> Java代码
> 
> ```java
>     @GetMapping("/test3")
>     @GlobalTransactional
>     public void test3() throws SQLException {
>         ConnectionProxy connection = (ConnectionProxy) dataSource.getConnection();
> 
>         String sql = "insert into uk(f1, f2, f3) values (?, ?, ?), (?, ?, ?) on duplicate key update f1=?";
>         PreparedStatementProxy ps = (PreparedStatementProxy) connection.prepareStatement(sql);
> 
>         ps.setInt(1, 1);
>         ps.setInt(2, 1);
>         ps.setInt(3, 1);
>         ps.setInt(4, 1);
>         ps.setInt(5, 2);
>         ps.setInt(6, 3);
>         ps.setInt(7, 5);
>         try {
>             ps.executeUpdate();
>         } finally {
>             IOUtil.close(ps);
>             IOUtil.close(connection);
>         }
>     }
> ```
> 
> 报错日志：
> 
> ```
> 2021-02-21 20:24:21.280 ERROR 320318 --- [nio-8430-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  OR (f1 = 1 )  OR (f2 = 2  and f3 = 3 )  OR ()  FOR UPDATE' at line 1] with root cause
> 
> java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  OR (f1 = 1 )  OR (f2 = 2  and f3 = 3 )  OR ()  FOR UPDATE' at line 1
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227) ~[druid-1.1.23.jar:1.1.23]
> 	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.buildTableRecords2(MySQLInsertOrUpdateExecutor.java:287) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.buildImage(MySQLInsertOrUpdateExecutor.java:265) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.beforeImage(MySQLInsertOrUpdateExecutor.java:250) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.executeAutoCommitFalse(MySQLInsertOrUpdateExecutor.java:103) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:140) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:340) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:184) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:139) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:114) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:122) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:54) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:65) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at cn.caohd.txproviderserver.controller.UserController.test3(UserController.java:286) ~[classes/:na]
> ```



> SQL里面的主键是auto_increment，并且没有主动赋值的时候，执行会报错，可以通过下面的代码复现。
> 
> 建表SQL
> 
> ```sql
> create table uk (
>     id int unsigned not null auto_increment primary key ,
>     f1 int unsigned not null unique ,
>     f2 int unsigned not null ,
>     f3 int unsigned not null ,
>     unique (f2, f3)
> );
> ```
> 
> Java代码
> 
> ```java
>     @GetMapping("/test3")
>     @GlobalTransactional
>     public void test3() throws SQLException {
>         ConnectionProxy connection = (ConnectionProxy) dataSource.getConnection();
> 
>         String sql = "insert into uk(f1, f2, f3) values (?, ?, ?), (?, ?, ?) on duplicate key update f1=?";
>         PreparedStatementProxy ps = (PreparedStatementProxy) connection.prepareStatement(sql);
> 
>         ps.setInt(1, 1);
>         ps.setInt(2, 1);
>         ps.setInt(3, 1);
>         ps.setInt(4, 1);
>         ps.setInt(5, 2);
>         ps.setInt(6, 3);
>         ps.setInt(7, 5);
>         try {
>             ps.executeUpdate();
>         } finally {
>             IOUtil.close(ps);
>             IOUtil.close(connection);
>         }
>     }
> ```
> 
> 报错日志：
> 
> ```
> 2021-02-21 20:24:21.280 ERROR 320318 --- [nio-8430-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  OR (f1 = 1 )  OR (f2 = 2  and f3 = 3 )  OR ()  FOR UPDATE' at line 1] with root cause
> 
> java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  OR (f1 = 1 )  OR (f2 = 2  and f3 = 3 )  OR ()  FOR UPDATE' at line 1
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.20.jar:8.0.20]
> 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227) ~[druid-1.1.23.jar:1.1.23]
> 	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.buildTableRecords2(MySQLInsertOrUpdateExecutor.java:287) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.buildImage(MySQLInsertOrUpdateExecutor.java:265) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec.mysql.MySQLInsertOrUpdateExecutor.beforeImage(MySQLInsertOrUpdateExecutor.java:250) ~[seata-all-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
> 	at io.seata.rm.datasource.exec. [...]

2021-02-23 05:08 UTC, huan415 commented
> 建表SQL：
> 
> ```sql
> create table uk (
>     id int unsigned not null auto_increment primary key ,
>     f1 int unsigned unique ,
>     f2 int unsigned ,
>     f3 int unsigned ,
>     unique (f2, f3)
> );
> ```
> 
> Java代码：
> 
> ```java
>     @GetMapping("/test3")
>     @GlobalTransactional
>     public void test3() throws SQLException {
>         ConnectionProxy connection = (ConnectionProxy) dataSource.getConnection();
> 
>         String sql = "insert into uk(f1, f2, f3) values (?, ?, ?) on duplicate key update f1=?";
>         PreparedStatement ps = connection.prepareStatement(sql);
> 
>         ps.setInt(1, 11);
>         ps.setNull(2, Types.INTEGER);
>         ps.setInt(3, 0);
>         ps.setInt(4, 8);
>         try {
>             ps.executeUpdate();
>             if (true) {
>                 throw new RuntimeException("123");
>             }
>         } finally {
>             IOUtil.close(ps);
>             IOUtil.close(connection);
>         }
>     }
> ```
> 
> 数据库当前的数据：
> ![image](https://user-images.githubusercontent.com/22959373/108628508-5b438480-7496-11eb-8832-944be1deb392.png)
> ConnectionContext的数据好像不太正常
> ![image](https://user-images.githubusercontent.com/22959373/108628534-7ca47080-7496-11eb-945c-298f438df0b5.png)

解决了

2021-03-02 09:24 UTC, xingfudeshi commented
![image](https://user-images.githubusercontent.com/24457941/109626956-172e3f00-7b7c-11eb-8526-ab55cf730c8f.png)
@huan415 CI failed.Please fix it.

2021-03-16 05:12 UTC, huan415 commented
> ![image](https://user-images.githubusercontent.com/24457941/109626956-172e3f00-7b7c-11eb-8526-ab55cf730c8f.png)
> @huan415 CI failed.Please fix it.

已解决

2021-03-17 07:28 UTC, xingfudeshi approved these changes
LGTM.

2021-04-06 05:41 UTC, ymwangzq requested changes

2021-04-06 05:41 UTC, ymwangzq commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLInsertRecognizer.java
> +        return isDuplicateKeyUpdate() ? SQLType.INSERT_ON_DUPLICATE_UPDATE : SQLType.INSERT;
有一些地方通过判断 sqlRecognizer.getSQLType() == SQLType.INSERT 做相应处理，这样的地方可能也需要一起改下，比如：io.seata.rm.datasource.AbstractConnectionProxy#prepareStatement(java.lang.String)

2021-04-07 02:46 UTC, ymwangzq requested changes

2021-04-07 02:46 UTC, ymwangzq commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +        Object result = statementCallback.execute(statementProxy.getTargetStatement(), args);
如果update 操作里有修改主键，可能还需要拦截掉。

2021-04-17 13:47 UTC, huan415 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLInsertRecognizer.java
> +        return isDuplicateKeyUpdate() ? SQLType.INSERT_ON_DUPLICATE_UPDATE : SQLType.INSERT;
其他的地方好像不需要加把。您举例的这个，我看注释是support oracle 10.2+，但是oracle没有这种语法。所以不需要吧

2021-04-17 13:47 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +        Object result = statementCallback.execute(statementProxy.getTargetStatement(), args);
拦截掉？什么意思，没明白

2021-04-18 02:43 UTC, ymwangzq commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +        Object result = statementCallback.execute(statementProxy.getTargetStatement(), args);
参考这个改动之前的版本 https://github.com/seata/seata/pull/3287/files
在 UpdateExecutor 里构造 beforeImage 的时候，会调用 com.kuaishou.infra.seata.rm.datasource.exec.AbstractDMLBaseExecutor#assertContainsPKColumnName
检查是否更新了主键。如果修改主键会导致beforeImage和afterImage对不上，无法回滚

2021-04-21 13:38 UTC, huan415 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
> +        Object result = statementCallback.execute(statementProxy.getTargetStatement(), args);
insert into  on duplicate key update.  主键不一样就是insert了，除非用唯一键来更新主键（on duplicate key update.后面更新主键），感觉这种写法很奇葩，但是最好也支持一下。所以UpdateExecutor是判断beforeImage和afterImage大小不一样，就认为是更新了主键直接抛异常？  所以这如果是update的情况下，也判断afterImage和afterImage不一样就抛异常不支持？

2021-05-03 06:07 UTC, caohdgege approved these changes
LGTM

2021-05-03 06:22 UTC, a364176773 requested changes

2021-05-03 06:22 UTC, a364176773 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLInsertRecognizer.java
> +import com.alibaba.druid.sql.ast.expr.*;
不允许import *

2021-05-03 13:16 UTC, a364176773 approved these changes
LGTM

2021-05-03 13:27 UTC, merged