feature: saga support loop execution on state
seata/seata pull request #3468
Opened 2021-01-18 03:19 UTC by anselleeyy

### Ⅰ. Describe what this PR did

Saga 单个state执行，支持配置 loop 属性，用于循环执行，该配置作用于单个 state，支持 ServiceTask、SubStateMachine、ScriptTask

配置如下：

``` json
FirstState": {
    "Type": "ServiceTask",
    ...,
    "Loop": {
        "Parallel": 3, // 支持并发执行循环任务
        "Collection": "collection", // 集合名称
        "ElementVariableName": "element",  // 集合元素名称
        "ElementIndexName": "loopCounter" // 集合下标名称，默认 loopCounter
    },
    "Input": [
        {
            ...,
            "element": "$.[element]",
            "loopCounter": "$.[loopCounter]"
        }
    ]
},
```

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-01-18 07:53 UTC, long187 requested changes

2021-01-20 11:29 UTC, long187 requested changes

2021-03-01 13:09 UTC, long187 requested changes

2021-03-04 11:21 UTC, anselleeyy commented on saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/LoopStartStateHandler.java
> +        context.removeVariable(DomainConstants.VAR_NAME_IS_LOOP_STATE);
fixed

2021-03-04 11:22 UTC, anselleeyy commented on saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/LoopStartStateHandler.java
> +        LoopContextHolder.clearCurrent(context);
fixed

2021-03-04 11:22 UTC, anselleeyy commented on saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/LoopStartStateHandler.java
> +                context.setVariable(DomainConstants.VAR_NAME_CURRENT_EXCEPTION_ROUTE, DomainConstants.STATE_TYPE_COMPENSATION_TRIGGER);
fixed

2021-03-26 08:39 UTC, long187 approved these changes
LGTM
Offline has been through many times, the design is OK

2021-04-20 03:50 UTC, a364176773 approved these changes
LGTM

2021-04-20 04:56 UTC, merged