Optimize:register the participating companies 、 pull request informat…
seata/seata pull request #3637
Opened 2021-04-15 04:18 UTC by lj2018110133

…ion,etc

### Ⅰ. Describe what this PR did
register the participating companies 、 pull request information、modify rootcontext,etc

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-04-15 14:30 UTC, a364176773 commented on changes/1.4.2.md
> +  - [nature80](https://github.com/nature80)
contributors列表要根据pr合并数进行排序

2021-04-15 15:54 UTC, caohdgege commented on changes/en-us/1.4.2.md
> +  - [Ifdevil](https://github.com/Ifdevil)
Ifdevil, litianyu1992, 13414850431, xuande 重复了

2021-04-15 15:54 UTC, caohdgege commented on changes/1.4.2.md
> +  - [Ifdevil](https://github.com/Ifdevil)
Ifdevil, litianyu1992, 13414850431, xuande 重复了

2021-04-18 04:57 UTC, a364176773 requested changes

2021-04-18 04:57 UTC, a364176773 commented on core/src/main/java/io/seata/core/context/RootContext.java
>              if (LOGGER.isInfoEnabled()) {
isInfoEnabled -> isDebugEnabled

2021-04-18 04:57 UTC, a364176773 commented on core/src/main/java/io/seata/core/context/RootContext.java
>              if (LOGGER.isInfoEnabled()) {
isInfoEnabled -> isDebugEnabled

2021-04-18 04:57 UTC, a364176773 commented on core/src/main/java/io/seata/core/context/RootContext.java
>              if (LOGGER.isInfoEnabled()) {
isInfoEnabled -> isDebugEnabled

2021-04-20 14:34 UTC, a364176773 approved these changes
LGTM @slievrly @jsbxyyx @l81893521

2021-04-22 06:42 UTC, slievrly commented
#3359 move to test module

2021-04-22 06:43 UTC, slievrly commented
#3365 move to test module

2021-04-22 06:48 UTC, slievrly commented
#3336 支持使用System.getProperty获取Netty配置参数

2021-04-22 06:51 UTC, slievrly commented
#3175 支持雪花算法时钟回拨

2021-04-22 06:51 UTC, lj2018110133 commented
> #3336 支持使用System.getProperty获取Netty配置参数

done

2021-04-22 06:52 UTC, lj2018110133 commented
> #3175 支持雪花算法时钟回拨

done

2021-04-22 06:52 UTC, lj2018110133 commented
> #3359 move to test module

done

2021-04-22 06:53 UTC, lj2018110133 commented
> #3365 move to test module

done

2021-04-22 06:53 UTC, slievrly commented
#3172 支持 AT 模式 undo_log 压缩模式

2021-04-22 06:55 UTC, slievrly commented
#3293 修复配置缓存获取值类型不匹配的问题

2021-04-22 06:57 UTC, slievrly commented
#3385 优化 GitHub Actions 配置，修复单测失败问题。

2021-04-22 07:05 UTC, lj2018110133 commented
> #3385 优化 GitHub Actions 配置，修复单测失败问题。

done

2021-04-22 10:21 UTC, slievrly commented
#3341 优化获取指定配置文件的路径格式问题

2021-04-22 10:23 UTC, slievrly commented
`#3383 优化 StatementProxyTest 测试用例` move to test module.

2021-04-22 10:29 UTC, slievrly commented
#3397 增加代码变更记录

2021-04-22 10:37 UTC, slievrly commented
#3380 优化 globalTransactionScanner 中的 DISABLE_GLOBAL_TRANSACTION listener

2021-04-22 10:39 UTC, slievrly commented
#3406 修复当config.txt中包含特殊字符时无法推送至 nacos 的问题。

2021-04-22 10:43 UTC, slievrly commented
#3420 优化枚举类的使用并添加单元测试。

2021-04-22 11:23 UTC, lj2018110133 commented
> #3420 优化枚举类的使用并添加单元测试。

It's all done

2021-04-22 11:37 UTC, slievrly commented
#3123 优化 seata-server 打包策略。

2021-04-22 11:42 UTC, slievrly commented
#3415 优化 maven 打包时清除 distribution 目录

2021-04-22 11:45 UTC, slievrly commented
#3316 优化读取配置值时属性bean未初始化的问题。

2021-04-22 11:48 UTC, slievrly commented
#2667 支持使用db和redis存储模式时密码的加解密。

2021-04-22 11:53 UTC, slievrly commented
#3408 修复jar运行模式第三方依赖分离打包时的NPE问题。

2021-04-22 11:56 UTC, slievrly commented
#3411 支持seata-server 线程池参数可配置。

2021-04-22 11:59 UTC, slievrly commented
#3215 优化seata-server 在file模式下启动时的reload逻辑。

2021-04-22 12:02 UTC, slievrly commented
#3431 修复在读取配置时Property Bean可能未初始化的问题

2021-04-22 12:09 UTC, slievrly commented
#3443 支持将seata-server的日志发送到logstash或kafka中。

2021-04-22 12:17 UTC, slievrly commented
#3439 调整springApplicationContextProvider order以使其可以在xml bean之前被调用

2021-04-22 12:19 UTC, slievrly commented
`#3458 还原被误删除的change log`  move to optimize  module。

2021-04-22 12:21 UTC, slievrly commented
#3371 支持 metric 按  applicationId 分组。

2021-04-22 12:23 UTC, slievrly commented
#3318  支持  CLIENT_TABLE_META_CHECKER_INTERVAL 可配置化。

2021-04-22 12:26 UTC, slievrly commented
#3451 修复autoCommit=true，全局锁竞争失败时的脏写问题。

2021-04-22 12:29 UTC, slievrly commented
#3466 优化使用equalsIgnoreCase() 进行字符串比较。

2021-04-22 12:31 UTC, slievrly commented
`#3156 修复嵌套代理类无法 获取target的问题 ` move to bugfix module。

2021-04-22 12:38 UTC, slievrly commented
`#3447 支持日志框架中事务上下文的打印` move to feature module。

2021-04-22 12:42 UTC, slievrly commented
#3481 修复当 consul client 抛出异常时导致刷新任务中断的问题。

2021-04-22 12:43 UTC, slievrly commented
#3485 删除 ConfigurationFactory 中无用的代码。

2021-04-22 12:46 UTC, slievrly commented
#3476 支持 server 参数传入hostname时自动将其转换为 ip。

2021-04-22 12:47 UTC, slievrly commented
#3505 删除  GlobalTransactionScanner 中无用的 if 判断。

2021-04-22 12:48 UTC, slievrly commented
#3500 修复 oracle 和 postgreSql 无法获取 column info 的问题。

2021-04-22 13:02 UTC, slievrly commented
#3402  修复更新SQL中字段名含有库名无法解析更新列的问题。

2021-04-22 13:30 UTC, slievrly commented
#3236 优化执行解锁操作的条件，减少不必要的 unlock 操作。

2021-04-22 13:33 UTC, slievrly commented
#3116 支持配置 apollo 配置中心配置 configService 和 cluster。

2021-04-22 13:35 UTC, slievrly commented
#3516 支持 consul 作为注册中心和配置中心时的 acl-token

2021-04-22 13:37 UTC, slievrly commented
#3228 支持自定义序列化插件。

2021-04-22 13:38 UTC, slievrly commented
#2933 支持mysql antlr sqlparser

2021-04-22 13:42 UTC, slievrly commented
#3531 修复RedisTransactionStoreManager 获取 brachTransaction 可能的 NPE 问题。

2021-04-22 13:43 UTC, slievrly commented
#3533 支持获取当前事务角色。

2021-04-22 13:44 UTC, slievrly commented
#3540 修复server发布打包时缺失文件的问题。

2021-04-22 13:46 UTC, slievrly commented
#3513 Saga SpringBeanService调用器支持切换  json 解析器。

2021-04-22 13:47 UTC, slievrly commented
#3549 统一DB存储模式下不同表中的xid字段的长度。

2021-04-22 14:03 UTC, slievrly commented
#3560 修复 Committing 状态的事务异步任务没有时间阈值和无法进行事务恢复的问题。

2021-04-22 14:06 UTC, slievrly commented
#3317 支持当zookeeper作为配置中心时从单node获取全部配置。

2021-04-22 14:08 UTC, slievrly commented
#3578 move to test module。

2021-04-22 14:09 UTC, slievrly commented
#3574  move to optimize module。

2021-04-22 14:10 UTC, slievrly commented
#3573 move to optimize module。

2021-04-22 14:12 UTC, slievrly commented
#3579 添加 StringFormatUtils 测试用例。

2021-04-22 14:15 UTC, slievrly commented
#3597 修复可能的 NPE问题。

2021-04-22 14:18 UTC, slievrly commented
#3631 优化 nacos-config.py 脚本的入参问题。

2021-04-22 14:19 UTC, slievrly commented
#3522 修复当 DML 影响行数为0时注册分支和插入undo_log的问题。

2021-04-22 14:22 UTC, slievrly commented
#3635 修复zookeeper 配置变更无法推送通知的问题。

2021-04-22 14:24 UTC, slievrly commented
#3638 优化 update 和 delete 的 SQL 不支持 join 的错误提示。

2021-04-23 16:42 UTC, slievrly approved these changes
LGTM

2021-04-23 17:40 UTC, merged