feature:support redis distributed lock to prevent TC competition
seata/seata pull request #3683
Opened 2021-04-28 06:00 UTC by lightClouds917

### Ⅰ. Describe what this PR did
feature:support redis distributed lock to prevent multiple TCs Competitive process the scheduled task，like retryRollbacking,retryCommitting......

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-04-30 15:38 UTC, a364176773 commented on changes/en-us/1.5.0.md
> +- [[#3683](https://github.com/seata/seata/pull/3683)] support redis distributed lock to prevent multi TC competition
contributor信息没有登记

2021-04-30 15:54 UTC, a364176773 requested changes

2021-04-30 15:54 UTC, a364176773 commented on common/src/main/java/io/seata/common/XID.java
> +        return ipAddress + ":" + port;
new StringBuilder

2021-04-30 15:54 UTC, a364176773 commented on script/config-center/config.txt
> +store.redis.distributedLockExpireTime=60
跟华栋的pr协商下,统一一个配置项

2021-04-30 15:54 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} release the {} distributed lock failed.", lockValue, lockKey, ex);
error

2021-04-30 15:54 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} acquired the {} distributed lock failed.", lockValue, lockKey, ex);
error

2021-05-06 03:12 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} acquired the {} distributed lock failed.", lockValue, lockKey, ex);
这两个日志级别，我考虑到出错后不影响全局的执行，所以都给的warn.

2021-05-06 03:21 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} acquired the {} distributed lock failed.", lockValue, lockKey, ex);
为什么调整成error就会影响全局执行？

2021-05-06 06:49 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} acquired the {} distributed lock failed.", lockValue, lockKey, ex);
这两个日志级别，我考虑到出错后不影响全局的执行，所以都给的warn.

2021-05-06 06:49 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} release the {} distributed lock failed.", lockValue, lockKey, ex);
这两个日志级别，我考虑到出错后不影响全局的执行，所以都给的warn.

2021-05-06 07:02 UTC, lightClouds917 commented on changes/en-us/1.5.0.md
> +- [[#3683](https://github.com/seata/seata/pull/3683)] support redis distributed lock to prevent multi TC competition
done

2021-05-06 07:02 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} release the {} distributed lock failed.", lockValue, lockKey, ex);
done

2021-05-06 07:02 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +            LOGGER.warn("The {} acquired the {} distributed lock failed.", lockValue, lockKey, ex);
done

2021-05-06 07:03 UTC, lightClouds917 commented on script/config-center/config.txt
> +store.redis.distributedLockExpireTime=60
ok

2021-05-20 11:07 UTC, lightClouds917 commented on changes/en-us/1.5.0.md
> +
done

2021-05-20 11:09 UTC, lightClouds917 commented on common/src/main/java/io/seata/common/XID.java
> +        return ipAddress + ":" + port;
done

2021-05-21 13:58 UTC, a364176773 requested changes

2021-05-21 13:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +    public static DistributedLocker getInstance() {
应该要包括了DB那块的单例,应该单独搞个factory来构建DistributedLocker的单例,理论上做成SPI也是可以的

2021-05-26 08:13 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/redis/lock/RedisDistributedLocker.java
> +    public static DistributedLocker getInstance() {
done

2021-06-02 14:03 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> -        return getRootSessionManager().scheduledLock(RETRY_ROLLBACKING);
为何不在getRootSessionManager().scheduledLock集中处理?

2021-06-04 11:04 UTC, lightClouds917 commented on server/src/test/java/io/seata/server/session/SessionHolderTest.java
> +import org.junit.jupiter.api.*;
done

2021-06-04 11:04 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/lock/distributed/DistributedLockerFactory.java
> +    private static final Map<String, DistributedLocker> DISTRIBUTED_LOCKER_MAP = new ConcurrentHashMap<>();
这个是一个统一的分布式锁工厂入口，不同功能的锁key不同，都在这里管理。map的原因是考虑到后续可能的拓展。

2021-06-04 11:04 UTC, lightClouds917 commented on server/src/test/java/io/seata/server/session/SessionHolderTest.java
> +import org.junit.jupiter.api.*;
done

2021-06-04 11:05 UTC, lightClouds917 commented on server/src/test/java/io/seata/server/session/redis/RedisDistributedLockerTest.java
> +    @Test
done

2021-06-04 11:06 UTC, lightClouds917 commented on server/src/test/java/io/seata/server/session/SessionHolderTest.java
> +        Assertions.assertEquals(true,SessionHolder.retryRollbackingLock());
done

2021-06-04 11:09 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> -        return getRootSessionManager().scheduledLock(RETRY_ROLLBACKING);
SessionManager接口的实现，就进入了RedisSessionManager，DataBaseSessionManager的具体实现了，分布式锁没法统一管理了。现在这种方式，在上层可以抽象一层。

2021-06-04 11:10 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> -        return getRootSessionManager().scheduledLock(RETRY_ROLLBACKING);
不过我考虑再往上推一层，在DefaultCoordinator里集中，SessionHolder暴漏一个方法，在DefaultCoordinator里调用时，传不同的参数去调用SessionHolder。这样unTxTimeoutCheckLock就能干掉七个方法了。

2021-06-09 16:26 UTC, caohdgege commented on server/src/main/java/io/seata/server/lock/distributed/DistributedLockerFactory.java
> +import java.util.Map;
调整一下import的顺序

2021-06-09 16:26 UTC, caohdgege commented on server/src/main/java/io/seata/server/lock/distributed/DistributedLockerFactory.java
> +    public static DistributedLocker getDistributedLocker(String dbType) {
dbType -> lockerType ?
因为这里除了dbType中的各种数据库类型外，还可能是file/redis，用dbType不是很贴切

2021-06-09 16:26 UTC, caohdgege commented on server/src/main/java/io/seata/server/storage/file/lock/FileDistributedLocker.java
> + * @author: zhongxiang.wang
@auther后面应该是不需要 : 的，其他文件也一起改一下？

2021-06-09 16:26 UTC, caohdgege commented on server/src/main/resources/META-INF/services/io.seata.core.store.DistributedLocker
> +io.seata.server.storage.file.lock.FileDistributedLocker
db的，是不是也应该有个空实现，即直接返回true的？不然在你的pr合并上去过之前，我的pr没合并之前，走db的是不是会报错？

2021-06-10 03:12 UTC, lightClouds917 commented on server/src/main/resources/META-INF/services/io.seata.core.store.DistributedLocker
> +io.seata.server.storage.file.lock.FileDistributedLocker
done

2021-06-10 03:12 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/file/lock/FileDistributedLocker.java
> + * @author: zhongxiang.wang
done

2021-06-13 16:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/lock/distributed/DistributedLockerFactory.java
> +    private static final Map<String, DistributedLocker> DISTRIBUTED_LOCKER_MAP = new ConcurrentHashMap<>();
我认为不存在tc同时使用一个以上的分布式锁实现,这是完全没有必要的

2021-06-13 17:01 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/db/lock/distributed/MysqlDistributedLocker.java
> +public class MysqlDistributedLocker implements DistributedLocker {
为什么要分开多个db的实现?如果按这么来,是不是lock和session那块还得分开多个db的实现?

2021-06-13 17:02 UTC, a364176773 commented on server/src/main/resources/META-INF/services/io.seata.core.store.DistributedLocker
> +io.seata.server.storage.db.lock.distributed.MysqlDistributedLocker
应该按照store mode实现,你这个pr无需关系db的实现,直接去掉相关实现吧

2021-06-18 11:36 UTC, lightClouds917 commented on server/src/main/resources/META-INF/services/io.seata.core.store.DistributedLocker
> +io.seata.server.storage.db.lock.distributed.MysqlDistributedLocker
done

2021-06-18 11:36 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/storage/db/lock/distributed/MysqlDistributedLocker.java
> +public class MysqlDistributedLocker implements DistributedLocker {
done

2021-06-19 16:13 UTC, a364176773 requested changes

2021-06-19 16:13 UTC, a364176773 commented on server/src/main/java/io/seata/server/lock/distributed/DistributedLockerFactory.java
> +                        DISTRIBUTED_LOCKER = new DefaultDistributedLocker();
这里直接输出异常日志,下面赋值比较优雅

2021-06-20 02:49 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/lock/distributed/DistributedLockerFactory.java
> +                        DISTRIBUTED_LOCKER = new DefaultDistributedLocker();
done

2021-06-21 05:27 UTC, a364176773 approved these changes
LGTM

2021-06-22 16:16 UTC, caohdgege approved these changes
LGTM

2021-06-22 16:18 UTC, merged