optimize: `JacksonUndoLogParser` supports to parse `LocalDateTime`
seata/seata pull request #3738
Opened 2021-05-17 17:01 UTC by wangliang181230

### Ⅰ. Describe what this PR did
optimize: `JacksonUndoLogParser` supports to parse `LocalDateTime`。
优化：`JacksonEndologParser`支持解析`LocalDateTime`。

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-05-18 05:17 UTC, a364176773 requested changes

2021-05-18 05:17 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParser.java
> +                gen.writeNumber(localDateTime.toInstant(ZoneOffset.ofHours(8)).toEpochMilli());
ZoneId.systemDefault()

2021-05-18 05:17 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParser.java
> +                return LocalDateTime.ofEpochSecond(timestamp / 1000, 0, ZoneOffset.ofHours(8));
精度丢失

2021-05-18 07:44 UTC, wangliang181230 commented on rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParser.java
> +                return LocalDateTime.ofEpochSecond(timestamp / 1000, 0, ZoneOffset.ofHours(8));
done

2021-05-18 09:39 UTC, wangliang181230 commented on rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParser.java
> +                gen.writeNumber(localDateTime.toInstant(ZoneOffset.ofHours(8)).toEpochMilli());
done

2021-05-20 09:12 UTC, a364176773 approved these changes
LGTM

2021-05-22 14:20 UTC, caohdgege approved these changes
LGTM

2021-05-22 15:53 UTC, merged

2021-11-17 06:34 UTC, zyplanke commented
验证情况：
测试OK的环境：spring-boot-starter2.4.11， seata 1.4.2，mysql-connector-java8.0.22
测试OK的环境：spring-boot-starter2.4.11， seata 1.3.0，mysql-connector-java8.0.22
报转换异常的环境：spring-boot-starter2.4.11， seata 1.4.2，mysql-connector-java8.0.23
报转换异常的环境：spring-boot-starter2.4.11， seata 1.4.2，mysql-connector-java8.0.24
报转换异常的环境：spring-boot-starter2.4.11， seata 1.4.2，mysql-connector-java8.0.26
结论：
1、MySQL版本不能高于8.0.22，高于则存在此LocalDataTime转换异常。 说明从8.0.23开始MySQL驱动调整了此类型定义。
2、与spring-boot-starter版本无关。 seata 1.4.2和seata 1.3.0都可以正常运行。
3、Seata官方说1.4.2修复此问题，实际还没有修复到位（至少MySQL≥8.0.23版本仍存在此问题）

2022-07-08 07:09 UTC, edifangyi commented
请问这个怎么用？？？

2022-07-08 10:08 UTC, wangliang181230 commented
这个是seata内置集成的，但似乎还有些问题。