seata config nacos支持yaml
seata/seata pull request #4001
Opened 2021-09-03 09:27 UTC by x-shadow-man

### Ⅰ. Describe what this PR did
解决 issue # 3829: seata server端读取nacos配置问题

### Ⅱ. Does this pull request fix one issue?

fixes: #3829 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-09-03 15:48 UTC, a364176773 commented
标题英文,以optimize: 开头

2021-09-03 15:49 UTC, a364176773 commented
![image](https://user-images.githubusercontent.com/19943636/132032996-f8474140-0ab3-49f0-9189-530e305e477b.png)
本地的git绑定一下你的github账号信息

2021-09-03 15:51 UTC, a364176773 requested changes

2021-09-03 15:51 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +import java.util.*;
不运行*的导入,不要变动原有的导入格式,不要变动你不需要改动的代码行

2021-09-03 15:51 UTC, a364176773 commented on config/seata-config-nacos/pom.xml
> +            <artifactId>spring-beans</artifactId>
单纯的配置中心,不要依赖spring的东西

2021-09-03 15:51 UTC, a364176773 commented
其它几个支持properties的配置中心请一起进行适配

2021-09-04 13:11 UTC, x-shadow-man commented
> 标题英文,以optimize: 开头

ok. done.

2021-09-05 14:43 UTC, a364176773 commented
> > 标题英文,以optimize: 开头
> 
> ok. done.

英文= -

2021-09-06 07:04 UTC, x-shadow-man commented
> > > 标题英文,以optimize: 开头
> > 
> > 
> > ok. done.
> 
> 英文= -



> ![image](https://user-images.githubusercontent.com/19943636/132032996-f8474140-0ab3-49f0-9189-530e305e477b.png)
> 本地的git绑定一下你的github账号信息

sorry, forget to change local github account! x-shadow-man is the right account.

2021-09-06 13:31 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/processor/ProcessorYaml.java
> +    private static void buildFlattenedMap(Map<String, Object> result, Map<String, Object> source, String path) {
PortHelper 有个bulidFlatMap函数 看下能否复用

2021-09-06 13:31 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +    private static final String DEFAULT_DATA_TYPE = "properties";
如果用户没配置,是否可以按.分割得到type?如果dataid没有.那么就按默认值

2021-09-07 02:52 UTC, chenlei3641 commented on config/seata-config-core/src/main/java/io/seata/config/processor/ProcessorYaml.java
> +    private static void buildFlattenedMap(Map<String, Object> result, Map<String, Object> source, String path) {
PortHelper 位于server包下，不便引入config

2021-09-07 03:06 UTC, chenlei3641 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +    private static final String DEFAULT_DATA_TYPE = "properties";
done

2021-09-08 02:10 UTC, x-shadow-man commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +import java.util.*;
ok.done

2021-09-08 08:10 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/processor/ProcessorYaml.java
> +    private static void buildFlattenedMap(Map<String, Object> result, Map<String, Object> source, String path) {
> PortHelper 位于server包下，不便引入config

我的意思是，你可以把他抽出来，放在common一些符合的工具类里，改一下server端代码，这样就达到复用了

2021-09-08 08:10 UTC, a364176773 commented on config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
> +        String dataType = FILE_CONFIG.getConfig(FILE_CONFIG_KEY_PREFIX + CONFIG_DATA_TYPE_KEY);
dataType通用一下，放在seata.config.dataType是不是好点，毕竟每个配置中心未来都是要支持properties和yaml，这个是个公共配置项

2021-09-08 09:34 UTC, x-shadow-man commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +import java.util.*;
fixed

2021-09-08 09:34 UTC, x-shadow-man commented on config/seata-config-nacos/pom.xml
> +            <artifactId>spring-beans</artifactId>
fixed

2021-09-09 01:32 UTC, chenlei3641 commented on config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
> +        String dataType = FILE_CONFIG.getConfig(FILE_CONFIG_KEY_PREFIX + CONFIG_DATA_TYPE_KEY);
done

2021-09-09 04:02 UTC, x-shadow-man commented on config/seata-config-core/src/main/java/io/seata/config/processor/ProcessorYaml.java
> +    private static void buildFlattenedMap(Map<String, Object> result, Map<String, Object> source, String path) {
fixed

2021-09-11 07:30 UTC, a364176773 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigProperties.java
> +     * properties,yaml(only type in nacos,zk)
properties, yaml(only type in nacos, zk)

2021-09-11 07:30 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +                        seataConfigNew = ConfigProcessor.processConfig(configInfo,getNacosDataType());
ConfigProcessor.processConfig(configInfo, getNacosDataType());

2021-09-11 07:30 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +                seataConfig = ConfigProcessor.processConfig(config,getNacosDataType());
ConfigProcessor.processConfig(config, getNacosDataType());

2021-09-11 07:30 UTC, a364176773 commented on config/seata-config-core/src/main/java/io/seata/config/processor/ProcessorYaml.java
> +    @Override
换个行到34行去

2021-09-14 06:28 UTC, x-shadow-man commented on config/seata-config-core/src/main/java/io/seata/config/processor/ProcessorYaml.java
> +    @Override
done

2021-09-14 07:33 UTC, a364176773 approved these changes
LGTM @xingfudeshi  PTAL

2021-09-14 09:58 UTC, xingfudeshi approved these changes
LGTM.

2021-09-14 15:03 UTC, merged