1.4.2分支支持并新增h2数据库新特性
seata/seata pull request #4126
Opened 2021-11-10 09:02 UTC by HongYan789

1.4.2分支支持并新增h2数据库新特性，望采纳，谢谢！！！

2021-11-10 09:08 UTC, a364176773 commented
非常欢迎你的贡献，麻烦基于develop进行一下冲突处理，并添加测试用例

2021-11-10 15:14 UTC, slievrly commented
conflicts has resolved.

2021-11-10 15:15 UTC, slievrly commented on all/pom.xml
> +                            <skipStagingRepositoryClose>true</skipStagingRepositoryClose>
remove this properties

2021-11-10 15:26 UTC, slievrly commented
@HongYan789 some check styles not pass.
![image](https://user-images.githubusercontent.com/8758457/141140872-dc1e7a6e-1920-4d8d-9ad7-b0c05e886ddb.png)

2021-11-11 05:42 UTC, a364176773 requested changes

2021-11-12 12:11 UTC, a364176773 commented
有新pr了，这个可以关了吧

2021-11-12 12:11 UTC, closed without merging