feature:init the console basic code
seata/seata pull request #4134
Opened 2021-11-12 12:20 UTC by lightClouds917

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

feature:init the console basic code

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-11-12 12:46 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/manager/BranchSessionServiceManager.java
> +                        BRANCH_SESSION_SERVICE = EnhancedServiceLoader.load(BranchSessionService.class, sessionMode);
都写controller了,直接用@service吧,别用spi了,格格不入

2021-11-12 12:54 UTC, a364176773 requested changes

2021-11-12 12:54 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +    private GlobalSessionVO convertGlobalSessionVO(ResultSet rs) throws SQLException {
convertGlobalSessionVO 放到 GlobalSessionVO 作为静态方法比较好,其它同理

2021-11-12 12:54 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +        return PageResult.success(list, list.size(), 0, 0, 0);
应该用result,而不是page,这里没有分页

2021-11-12 12:54 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +@LoadLevel(name = "redis", scope = Scope.PROTOTYPE)
@Service

2021-11-12 12:54 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/result/Result.java
> +    private List<T> data;
data为什么一定是list?

2021-11-12 12:54 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/service/GlobalSessionService.java
> +    GlobalSessionVO queryByXid(String xid);
Result

2021-12-05 01:24 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +        return PageResult.success(list, list.size(), 0, 0, 0);
done

2021-12-05 01:24 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +    private GlobalSessionVO convertGlobalSessionVO(ResultSet rs) throws SQLException {
done

2021-12-05 01:25 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/result/Result.java
> +    private List<T> data;
done

2021-12-05 01:25 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/service/GlobalSessionService.java
> +    GlobalSessionVO queryByXid(String xid);
done

2021-12-05 01:25 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +@LoadLevel(name = "redis", scope = Scope.PROTOTYPE)
done

2021-12-06 14:32 UTC, lightClouds917 commented
控制台基础代码pr概览：
主要是mvc结构，本pr主要是提供基础的框架，未做过多的具体接口实现：
1.db,redis,file三种模式下的branchSession,globalSession,lock的controller，service和serviceImpl框架；
2.2个具体的接口jdbc原生方式实现样例；
3.单个返回对象和分页列表返回对象统一包装类的基础代码实现；
4.bean选择使用springboot的@ConditionalOnExpression(SPEL)的简单方式，支持多个条件生效；
5.2中具体实现接口的sql；
6.上次会议中确定的6个基础的接口预留；

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/controller/BranchSessionController.java
> +@RequestMapping("seata/console/branchSession")
感觉无需加上seata前缀

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/controller/GlobalLockController.java
> +@RequestMapping("seata/console/globalLock")
同上

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/controller/GlobalSessionController.java
> +@RequestMapping("seata/console/globalSession")
同上

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.java
> +@ConditionalOnExpression("#{'${seata.store.mode}'.equals('db') and '${seata.store.session.mode}'.equals('db')}")
不应该是并且关系,应该是or,而不是and

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalLockDBServiceImpl.java
> +@ConditionalOnExpression("#{'${seata.store.mode}'.equals('db') and '${seata.store.lock.mode}'.equals('db')}")
同上

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +@ConditionalOnExpression("#{'${seata.store.mode}'.equals('db') and '${seata.store.session.mode}'.equals('db')}")
同上

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/BranchSessionRedisServiceImpl.java
> +@ConditionalOnExpression("#{'${seata.store.mode}'.equals('redis') and '${seata.store.session.mode}'.equals('redis')}")
同上

2021-12-06 14:58 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +@ConditionalOnExpression("#{'${seata.store.mode}'.equals('redis') and '${seata.store.lock.mode}'.equals('redis')}")
同上

2021-12-09 08:55 UTC, a364176773 commented on server/src/main/java/io/seata/server/ServerApplicationListener.java
> +        environment.getPropertySources().addFirst(new PropertiesPropertySource(key, pro));
直接往system.setproperty就行了，这个值除了spring，没地方会取

2021-12-09 08:55 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.java
> +@ConditionalOnExpression("#{'db'.equals(environment.getProperty('sessionMode'))}")
直接equals.${sessionMode}会有问题吗？

2021-12-09 08:55 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalLockDBServiceImpl.java
> +@ConditionalOnExpression("#{'db'.equals(environment.getProperty('lockMode'))}")
同上

2021-12-09 09:36 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.java
> +@ConditionalOnExpression("#{'db'.equals(environment.getProperty('sessionMode'))}")
测了一把不行，这个spel表达式是从bean里取的。

2021-12-09 11:52 UTC, a364176773 approved these changes
LGTM

2021-12-13 11:50 UTC, merged

2021-12-16 10:50 UTC, Pinocchio2018 commented on server/src/main/java/io/seata/server/ServerApplicationListener.java
> +        System.setProperty("sessionMode",
![image](https://user-images.githubusercontent.com/24909409/146357896-ea102fbf-6703-463f-b961-abc54963482f.png)
if I config  `service-port` , this line will not execute
```
 server:
    service-port: 8091
```