add dataId in config args
seata/seata pull request #4255
Opened 2022-01-02 05:30 UTC by zw201913

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-01-02 06:14 UTC, a364176773 requested changes

2022-01-02 06:14 UTC, a364176773 commented on config/seata-config-consul/src/main/java/io/seata/config/consul/ConsulConfiguration.java
> +import io.seata.config.*;
不允许导入*

2022-01-02 06:14 UTC, a364176773 commented on config/seata-config-etcd3/src/main/java/io/seata/config/etcd3/EtcdConfiguration.java
> +	private static String getRealDataId() {
code format

2022-01-02 06:14 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +import io.seata.config.*;
不要改动无需改动的import

2022-01-02 06:14 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> -    private static volatile NacosConfiguration instance;
不要改动没改动过的代码块

2022-01-05 12:58 UTC, a364176773 commented on config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
> +	private static final String CONFIG_DATA_ID_KEY = "dataId";
code format

2022-01-05 13:00 UTC, a364176773 commented on config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
> +    private static final String CONFIG_DATA_ID_KEY = "dataId";
都叫dataid,而且组合起来的key都一样,为何不放在AbstractConfiguration?

2022-01-05 13:00 UTC, a364176773 commented on config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
> +    private static String getConfigDataIdKey() {
同上

2022-01-05 13:01 UTC, a364176773 commented
script文件夹里的client相关file.conf yaml properties补充下对应的配置示例
server模块的example yml也补充一下

2022-01-05 15:11 UTC, a364176773 approved these changes
LGTM

2022-02-20 14:11 UTC, a364176773 commented
![image](https://user-images.githubusercontent.com/19943636/154846808-d086cfaa-772c-4a49-881f-3292bb615d08.png)
请根据ci提示 修复代码问题

2022-02-25 01:52 UTC, wangliang181230 commented
英文的 1.5.0.md 也补充一下内容。

2022-03-17 16:11 UTC, slievrly reviewed
from the point of view of implementation is no problem, but need to be further abstract design.

2022-08-31 07:43 UTC, closed without merging