feature：Realize the interface of console: get global session in the file mode
seata/seata pull request #4268
Opened 2022-01-06 01:45 UTC by miaoxueyu

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

query global session in the file mode

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-01-06 03:56 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +import java.util.*;
不允许导入*，并且java的包要在最上层

2022-01-06 03:56 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +                .stream()
用并行流是不是好一些

2022-01-06 03:56 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +import static java.util.Objects.isNull;
@author 里加上你的githubid

2022-01-06 14:13 UTC, lightClouds917 requested changes

2022-01-06 14:16 UTC, lightClouds917 commented
add change log of .md

2022-01-06 14:18 UTC, lightClouds917 commented
please add test case

2022-01-07 07:46 UTC, miaoxueyu commented
all right

2022-01-09 07:44 UTC, GoodBoyCoder commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +        if (param.getPageSize() == 0 || param.getPageNum() == 0) {
maybe "<0" is also an error parameter

2022-01-11 12:05 UTC, miaoxueyu commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +        final Collection<GlobalSession> allSessions = SessionHolder.getRootSessionManager().allSessions();
allSessions是从map的values里拿出来的   不可能为null只能为空列表

2022-01-13 14:55 UTC, miaoxueyu commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +        final Collection<GlobalSession> allSessions = SessionHolder.getRootSessionManager().allSessions();
同学   我这个PR已经写完啦   现在还差什么流程才能合并呀

2022-01-13 15:05 UTC, miaoxueyu reviewed
feature：Realize the interface of console: get global session in the file mode #4268

2022-01-14 16:06 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +    private List<GlobalSessionVO> convert(List<GlobalSession> filteredSessions) {
convert 不应该放在service中建议放在SessionConverter

2022-01-14 16:06 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
> +    private Set<BranchSessionVO> convert(ArrayList<BranchSession> branchSessions) {
同上

2022-01-17 06:01 UTC, Pinocchio2018 commented on changes/en-us/1.5.0.md
> +  - [miaoxueyu](https://github.com/miaoxueyu)
这里重复啦

2022-01-17 06:16 UTC, miaoxueyu commented on changes/en-us/1.5.0.md
> +  - [miaoxueyu](https://github.com/miaoxueyu)
好眼力呀  我改好啦

2022-01-17 06:21 UTC, miaoxueyu commented on changes/en-us/1.5.0.md
> +  - [miaoxueyu](https://github.com/miaoxueyu)
我这个PR打开有好久啦，大概还需要经过什么步骤才能合上去鸭

2022-01-17 06:24 UTC, Pinocchio2018 commented on changes/1.5.0.md
> +  - [miaoxueyu](https://github.com/miaoxueyu)
这里重复啦

2022-01-17 06:36 UTC, miaoxueyu commented on changes/1.5.0.md
> +  - [miaoxueyu](https://github.com/miaoxueyu)
OK啦

2022-01-17 07:21 UTC, a364176773 approved these changes
LGTM

2022-01-22 02:23 UTC, lightClouds917 approved these changes
LGTM

2022-01-22 03:33 UTC, merged

2022-02-05 15:53 UTC, slievrly commented on common/src/main/java/io/seata/common/exception/InvalidParamException.java
> +public class InvalidParamException extends RuntimeException {
why not. use `IllegalArgumentException` in `java.lang` package.