query redis globalSession code
seata/seata pull request #4281
Opened 2022-01-10 15:23 UTC by doubleDimple

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-01-12 01:33 UTC, doubleDimple commented
redis分页需要的总数total目前暂时用keys获取的，暂时没想到好的方法，还是不要这个total前端没法统计总页数，第一次提交开源代码代码写的不好的地方请多多指教

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +    private static final String DEFAULT_REDIS_SEATA_GLOBAL_LOCK_PREFIX = "SEATA_GLOBAL_LOCK";
我觉得你可以将redis共用的一些prefix提取成一个redismode的Constants

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/BranchSessionRedisServiceImpl.java
> +        return PageResult.success(branchSessionVOS,branchSessionVOS.size(),0,branchSessionVOS.size());
queryByXid 进行 code format

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +
多余空行

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +    private Integer checkParams(GlobalSessionParam param) {
与lock复用该代码

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +    private Set<BranchSessionVO> converToBranchSession(ArrayList<BranchSession> branchSessions) {
放到SessionConverter

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +    private void convertToVos(List<GlobalSessionVO> result,List<GlobalSession> globalSessions) {
放到SessionConverter

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +            if (isNotBlank(param.getApplicationId())){
打debug日志

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +            if (isNotBlank(param.getTransactionName())){
打debug日志

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +    private static final String REDIS_SEATA_GLOBAL_PREFIX_KEYS = "SEATA_GLOBAL_*";
= REDIS_SEATA_GLOBAL_PREFIX + "*"

2022-01-14 16:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +                xids.parallelStream().forEach(xid -> {
并行流中进行globalsessions.add会出现线程安全问题吗?ArrayList是线程不安全的

2022-01-15 06:19 UTC, caohdgege commented
pr描述里面改一下，应该是 fixes #xxxx, 这样GitHub才会在pr合并之后自动关闭issue

2022-01-15 09:11 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +    private static final String DEFAULT_REDIS_SEATA_GLOBAL_LOCK_PREFIX = "SEATA_GLOBAL_LOCK";
get

2022-01-15 09:11 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/BranchSessionRedisServiceImpl.java
> +        return PageResult.success(branchSessionVOS,branchSessionVOS.size(),0,branchSessionVOS.size());
get

2022-01-15 09:11 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +
get

2022-01-15 09:11 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +    private Integer checkParams(GlobalSessionParam param) {
get

2022-01-15 09:12 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +    private Set<BranchSessionVO> converToBranchSession(ArrayList<BranchSession> branchSessions) {
get

2022-01-15 09:12 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +    private void convertToVos(List<GlobalSessionVO> result,List<GlobalSession> globalSessions) {
get

2022-01-15 09:12 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +            if (isNotBlank(param.getApplicationId())){
get

2022-01-15 09:12 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +            if (isNotBlank(param.getTransactionName())){
get

2022-01-15 09:12 UTC, doubleDimple commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +    private static final String REDIS_SEATA_GLOBAL_PREFIX_KEYS = "SEATA_GLOBAL_*";
get

2022-01-15 09:12 UTC, doubleDimple commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +                xids.parallelStream().forEach(xid -> {
get

2022-01-17 05:39 UTC, doubleDimple commented
update finished

2022-01-17 08:31 UTC, doubleDimple commented
update finished，please review again

2022-01-24 12:23 UTC, doubleDimple commented on core/src/main/java/io/seata/core/constants/RedisKeyConstants.java
> + * @author doubleDimple
grt

2022-01-24 12:23 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +                logger.debug("not supported according to tableName or branchId query");
get

2022-01-25 02:15 UTC, doubleDimple commented on server/src/test/java/PageTest.java
> +    public static void main(String[] args) {
get

2022-01-25 02:15 UTC, doubleDimple commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +            return list.stream().collect(Collectors.summingLong(value -> value));
get

2022-01-25 02:49 UTC, doubleDimple commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +    public List<GlobalSession> findGlobalSessionByStatusWithPage(SessionCondition sessionCondition, boolean withBranchSessions) {
get

2022-02-04 14:53 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/BranchSessionRedisServiceImpl.java
> +import com.google.common.collect.Lists;
不要使用Lists,直接new

2022-02-04 14:53 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +import com.google.common.collect.Lists;
同上

2022-02-04 14:53 UTC, a364176773 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +    private Logger logger = LoggerFactory.getLogger(GlobalLockRedisServiceImpl.class);
要么getclass(),要么就staic final Logger LOGGER

2022-02-04 14:53 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionCondition.java
> +    public SessionCondition(){
还原一下,需要空格

2022-02-04 14:53 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +            GlobalSession globalSession = this.readSession(sessionCondition.getXid(),withBranchSessions);
code formatting,下面那行也是

2022-02-04 14:53 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +            try (Jedis jedis = JedisPooledFactory.getJedisInstance()) {
Pipeline pipelined = jedis.pipelined();Pipeline pipelined = jedis.pipelined();

2022-02-06 09:43 UTC, lightClouds917 requested changes

2022-02-06 09:43 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +            Map<String, String> map = jedis.hgetAll(key);
1.根据xid作为key时，查询的key-value，value可能是个字符串列表吧，比如这个branchId下有多行rawLock.(例如：SEATA_LOCK_jdbc:mysql://116.62.62.26/seata-order^^^order^^^2188;SEATA_LOCK_jdbc:mysql://116.62.62.26/seata-storage^^^storage^^^1)；
2.这个key-value直接map转对象，应该会有问题。

2022-02-06 09:43 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +            return PageResult.failure(ParameterRequired.getErrCode(),"not support request param");
这个提示信息，需要明确：让用户知道具体哪个参数不支持；或者仅支持哪几个参数。让用户看到后知道具体的问题在哪里。

2022-02-06 09:43 UTC, lightClouds917 commented on core/src/main/java/io/seata/core/constants/RedisKeyConstants.java
> +    public static final String DEFAULT_REDIS_SEATA_GLOBAL_LOCK_PREFIX = "SEATA_GLOBAL_LOCK";
这几个常量重复定义了。RedisLocker也有一份。两边统一用一个吧。都用你的也行，统一一下。

2022-02-06 09:43 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +            return PageResult.success(globalLockVos,total,param.getPageNum(),param.getPageSize());
total没有赋值

2022-02-06 09:43 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +
不必要的空格删除了。

2022-02-06 09:43 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +    private Logger logger = LoggerFactory.getLogger(GlobalLockRedisServiceImpl.class);
这个logger没用就删掉。

2022-02-07 14:08 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/BranchSessionRedisServiceImpl.java
> +import com.google.common.collect.Lists;
get

2022-02-07 14:09 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +import com.google.common.collect.Lists;
get

2022-02-07 14:10 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +    private Logger logger = LoggerFactory.getLogger(GlobalLockRedisServiceImpl.class);
get

2022-02-07 14:13 UTC, doubleDimple commented on server/src/main/java/io/seata/server/session/SessionCondition.java
> +    public SessionCondition(){
get

2022-02-07 14:15 UTC, doubleDimple commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +            GlobalSession globalSession = this.readSession(sessionCondition.getXid(),withBranchSessions);
get

2022-02-07 14:46 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +            return PageResult.success(globalLockVos,total,param.getPageNum(),param.getPageSize());
get

2022-02-07 15:00 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +            return PageResult.failure(ParameterRequired.getErrCode(),"not support request param");
get

2022-02-08 13:16 UTC, doubleDimple commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +            try (Jedis jedis = JedisPooledFactory.getJedisInstance()) {
get

2022-02-11 04:29 UTC, Bughue commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +            if (isBlank(param.getXid()) && param.getStatus() == null) {
这个if条件跟上面的if完全一样，这里是进不来的吧？

2022-02-13 00:08 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +            if (isBlank(param.getXid()) && param.getStatus() == null) {
get

2022-02-22 02:12 UTC, lightClouds917 approved these changes

2022-02-22 02:22 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +        } else if (isNotBlank(param.getTableName()) && isNotBlank(param.getPk()) && isNotBlank(param.getResourceId())) {
上次开会的时候新增的功能，要实现通过这三个参数来查询

2022-02-22 02:23 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalSessionRedisServiceImpl.java
> +            return PageResult.success(result,0,param.getPageNum(),param.getPageSize());
get

2022-02-22 02:23 UTC, doubleDimple commented on server/src/main/java/io/seata/server/console/impl/redis/GlobalLockRedisServiceImpl.java
> +                List<String> rowLoclKeys = new ArrayList<>();
get

2022-02-23 01:50 UTC, a364176773 requested changes
不要有任何地方与下行代码间隔两行

2022-02-23 01:50 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionCondition.java
> +
删掉

2022-02-23 01:50 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/SessionConverter.java
> +
删掉空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
> +
删掉空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisQueryConsolTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisQueryConsolTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisQueryConsolTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisQueryConsolTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisQueryConsolTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisTransactionStoreManagerTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisTransactionStoreManagerTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisTransactionStoreManagerTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisTransactionStoreManagerTest.java
> +
删除空行

2022-02-23 01:50 UTC, a364176773 commented on server/src/test/java/io/seata/server/session/redis/RedisTransactionStoreManagerTest.java
> +
删除空行

2022-02-24 06:40 UTC, a364176773 approved these changes
LGTM

2022-02-24 07:05 UTC, Bughue approved these changes

2022-02-24 09:50 UTC, merged