feature: Realize the interface of console: get global session and global lock in the db mode
seata/seata pull request #4320
Opened 2022-01-19 15:53 UTC by lvekee

### Ⅰ. Describe what this PR did
Realize the interface of console: get global session and global lock in the db mode

### Ⅱ. Does this pull request fix one issue?
fixes #4256.
fixes #4257.

2022-01-20 11:12 UTC, lightClouds917 commented
1.readme.md添加一下pr记录；
2.如果自测还没完成，就加个[WIP]前缀，自测通过了再去掉，我们再详细的review；
3.实现类author把自己添加一下；

2022-02-11 03:14 UTC, Bughue commented
```
 public static String countSql(String sourceSql, String dbType) {
        switch (dbType) {
            case "mysql":
            case "h2":
            case "postgresql":
            case "oceanbase":
            case "oracle":
                return sourceSql.replaceAll("(?i)(?<=select)(.*)(?=from)", " count(1) ");
            default:
                throw new NotSupportYetException("PageUtil not support this dbType:" + dbType);
        }
    }
```

这里变量是不是有点魔鬼，下面这样是不是好一点（或者SUPPORT_DB应该放在常量类里面）

```
public static final List<String> SUPPORT_DB = Arrays.asList("mysql", "h2","postgresql","oceanbase","oracle");
public static String countSql(String sourceSql, String dbType) {
        if(SUPPORT_DB.contains(dbType)){
                return sourceSql.replaceAll("(?i)(?<=select)(.*)(?=from)", " count(1) ");
        }else {
                throw new NotSupportYetException("PageUtil not support this dbType:" + dbType);
        }
    }
```

2022-02-11 03:23 UTC, Bughue commented on server/src/main/java/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.java
> +            throw new IllegalArgumentException("xid is not blank");
这里的exception信息应该是"xid is blank"或者"xid should not be blank"吧

2022-02-11 03:26 UTC, Bughue commented on common/src/main/java/io/seata/common/util/PageUtil.java
> +    }
这个抽一下是不是好点
```
public static final List<String> SUPPORT_DB = Arrays.asList("mysql", "h2","postgresql","oceanbase","oracle");
public static String countSql(String sourceSql, String dbType) {
        if(SUPPORT_DB.contains(dbType)){
                return sourceSql.replaceAll("(?i)(?<=select)(.*)(?=from)", " count(1) ");
        }else {
                throw new NotSupportYetException("PageUtil not support this dbType:" + dbType);
        }
    }
```

2022-02-11 03:32 UTC, Bughue commented on server/src/main/java/io/seata/server/console/controller/GlobalSessionController.java
> +    @PostMapping("query")
方法的path是不是应该统一加上  /

2022-02-11 03:48 UTC, Bughue commented on common/src/main/java/io/seata/common/util/PageUtil.java
> +     */
注释错了

2022-02-11 03:57 UTC, Bughue commented on core/src/main/java/io/seata/core/store/db/sql/log/AbstractLogStoreSqls.java
> +    public static final String WHERE_PLACEHOLD = " #where# ";
这些place hold要不要抽个类出来？现在已经有两个类都有 #where# 了

2022-02-11 04:15 UTC, Bughue commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +        return PageResult.success(list, count, (count / param.getPageSize()) + 1, param.getPageNum(), param.getPageSize());
如果count正好能把pageSize除尽的话，这里就会多一页出来。建议再搞个common方法处理掉count、pageNum和pageSize。

2022-02-11 04:23 UTC, Bughue commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +        return PageResult.success(list, count, (count / param.getPageSize()) + 1, param.getPageNum(), param.getPageSize());
如果count正好能把pageSize除尽的话，这里就会多一页出来。而且我看隔壁写的pageResult类加了个方法，可以把pages这个参数去掉，他会自动帮你算的。

2022-02-23 12:41 UTC, lightClouds917 approved these changes

2022-02-23 12:41 UTC, lightClouds917 commented on common/src/main/java/io/seata/common/util/PageUtil.java
> +    public static String pageSql(String sourceSql, String dbType, int pageNum, int pageSize) {
加测试用例

2022-02-23 12:41 UTC, lightClouds917 commented on common/src/main/java/io/seata/common/util/PageUtil.java
> +    public static String countSql(String sourceSql, String dbType) {
加测试用例

2022-02-25 12:07 UTC, lightClouds917 requested changes

2022-02-25 12:07 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.java
> +            ps = conn.prepareStatement(branchSessionSQL);
try里可以声明多个资源的。

2022-02-25 12:07 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java
> +            ps = conn.prepareStatement(querySessionSql);
try里可以声明多个资源的。

2022-02-25 12:15 UTC, lightClouds917 commented
lock和session里有部分代码可以公用，是否可以考虑抽取一下。

2022-03-04 07:33 UTC, lightClouds917 approved these changes
LGTM

2022-03-06 12:24 UTC, a364176773 approved these changes
LGTM

2022-03-06 13:10 UTC, merged

2022-03-11 15:47 UTC, slievrly commented on common/src/main/java/io/seata/common/util/PageUtil.java
> +            case "mysql":
io.seata.core.constants.DBType

2022-03-11 15:50 UTC, slievrly commented on core/src/main/java/io/seata/core/store/db/sql/lock/LockStoreSql.java
> +    String getAllLockSql(String lockTable, String whereCondition);
Non compliance with design principles.