optimize: skip reload for redis & db
seata/seata pull request #4393
Opened 2022-02-18 14:29 UTC by caohdgege

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
1. redis和db模式下，不扫描当前的所有globalsession
2. file模式下，启动时，Committing和CommitRetrying不进行加锁
3. 改几个typo，有个线程池没关，一并关闭一下

### Ⅱ. Does this pull request fix one issue?

fixes #3537

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-02-19 15:13 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                            // To do nothing
为什么不进行remove?

2022-02-23 03:49 UTC, wangliang181230 commented
![Uploading 图片.png…]()

2022-03-02 06:41 UTC, a364176773 commented on changes/1.5.0.md
> +  - [[#4353](https://github.com/seata/seata/pull/4353)] 为 `seata-all.jar` 瘦身。
这个可以删掉。。。。下面有了

2022-03-03 12:55 UTC, caohdgege commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +            CompletableFuture.runAsync(() -> {
不需要恢复，但是这个执行时间还是比较长的，放异步可能好一点，不需要霸占启动的时间

2022-03-03 12:56 UTC, caohdgege commented on changes/1.5.0.md
> +  - [[#4353](https://github.com/seata/seata/pull/4353)] 为 `seata-all.jar` 瘦身。
好像是。。。我删一下。。。

2022-03-03 13:01 UTC, caohdgege commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                            // To do nothing
要remove，补一下

2022-03-03 13:01 UTC, caohdgege commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +        if (storeMode == StoreMode.FILE) {
我这里想的是一步是需要重新加载数据，然后第二步是进行分配和removeerrorstatus

2022-03-03 15:44 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +        if (storeMode == StoreMode.FILE) {
> 我这里想的是一步是需要重新加载数据，然后第二步是进行分配和removeerrorstatus

放在上面也一样加载了数据没变呀,只不过这个if没必要,放到上面那个if里一起就行了

2022-03-03 15:45 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +            CompletableFuture.runAsync(() -> {
> 不需要恢复，但是这个执行时间还是比较长的，放异步可能好一点，不需要霸占启动的时间

我的意思是db和redis数据除了committed和rollbacked还有finish这三个,对其他数据无需reload,定时任务本身就会处理其他状态

2022-03-05 14:14 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                    ROOT_SESSION_MANAGER.findGlobalSessions(searchCondition);
redis目前一次性捞出了所有,db是限制100条所以需要继续查

2022-03-05 14:14 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                        removeInErrorState(removeGlobalSession);
failed状态的似乎不应该删除,建议failed状态的改为打日志输出让用户介入处理吧

2022-03-05 14:44 UTC, caohdgege commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                    ROOT_SESSION_MANAGER.findGlobalSessions(searchCondition);
https://github.com/seata/seata/pull/4431/files 合并之后就都是查limit了，所以都循环查即可。

2022-03-06 12:07 UTC, a364176773 requested changes

2022-03-06 12:07 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/file/session/FileSessionManager.java
> +                if (!Objects.equals(condition.getTransactionId(), globalSession.getTransactionId())) {
Objects.equals(condition.getTransactionId(), globalSession.getTransactionId())
found.add(globalSession);
return
这样是不是更好,transactionid是为一个,只可能有一个globalsession,找到后无需后续的遍历了

2022-03-06 12:07 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/file/session/FileSessionManager.java
> +                if (!Objects.equals(condition.getXid(), globalSession.getXid())) {
同下

2022-03-06 12:07 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                            lockBranchSessions(globalSession.getSortedBranches());
if (GlobalStatus.Rollbacking.equals(globalSession.getStatus())) {
                                globalSession.getBranchSessions().parallelStream().forEach(branchSession -> {
                                    branchSession.setLockStatus(LockStatus.Rollbacking);
                                });
这段代码要留着,否者重启后file的lock就变得没有状态,无法快速竞争锁失败了

2022-03-07 03:04 UTC, a364176773 commented on server/src/main/java/io/seata/server/storage/file/session/FileSessionManager.java
> +                if (!Objects.equals(condition.getXid(), globalSession.getXid())) {
是同上，这个顺序咋变了。。。。

2022-03-07 15:50 UTC, slievrly commented on server/src/main/java/io/seata/server/session/SessionHelper.java
> +        LOGGER.error("Thr Global session {} is in failed status, please handle it manually.", globalSession.getXid());
Thr ?

2022-03-07 15:52 UTC, slievrly commented on server/src/main/java/io/seata/server/session/SessionHelper.java
> +        LOGGER.error("Thr Global session {} is in failed status, please handle it manually.", globalSession.getXid());
same above, pay attention to the case of words.

2022-03-07 16:08 UTC, slievrly commented on server/src/main/java/io/seata/server/session/SessionHolder.java
>                              lockBranchSessions(globalSession.getSortedBranches());
why status=`Committing` or `CommitRetrying`  need lock?

2022-03-07 16:19 UTC, slievrly commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                    errorStatusGlobalSessions = ROOT_SESSION_MANAGER.findGlobalSessions(searchCondition);
may  be return null ?

2022-03-08 15:57 UTC, caohdgege commented on server/src/main/java/io/seata/server/session/SessionHolder.java
>                              lockBranchSessions(globalSession.getSortedBranches());
这个是跟之前的逻辑保持一致的，看了一下代码，改成这两个状态之前都已经执行过releaseGlobalSessionLock了，可以不用lock

2022-03-08 16:01 UTC, caohdgege commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                            lockBranchSessions(globalSession.getSortedBranches());
为啥其他几个Rollback相关的状态不需要的？

2022-03-08 16:10 UTC, caohdgege commented on server/src/main/java/io/seata/server/storage/file/session/FileSessionManager.java
> +                if (!Objects.equals(condition.getTransactionId(), globalSession.getTransactionId())) {
done

2022-03-08 16:10 UTC, caohdgege commented on server/src/main/java/io/seata/server/storage/file/session/FileSessionManager.java
> +                if (!Objects.equals(condition.getXid(), globalSession.getXid())) {
啥顺序？

2022-03-09 14:36 UTC, a364176773 commented on server/src/main/java/io/seata/server/session/SessionHolder.java
> +                            lockBranchSessions(globalSession.getSortedBranches());
> 为啥其他几个Rollback相关的状态不需要的？

rollbacked应该不需要其他都需要,补充一下咯

2022-03-11 02:02 UTC, lightClouds917 approved these changes
LGTM

2022-03-11 15:46 UTC, caohdgege commented on server/src/main/java/io/seata/server/session/SessionHelper.java
> +
done

2022-03-12 16:03 UTC, slievrly approved these changes
LGTM

2022-03-12 16:04 UTC, merged