【WIP】Transaction timeout judgment is performed on the TM side
seata/seata pull request #4445
Opened 2022-03-07 11:24 UTC by miaoxueyu

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
Transaction timeout judgment is performed on the TM side

### Ⅱ. Does this pull request fix one issue?

fixes #4371

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-03-07 12:13 UTC, a364176773 requested changes

2022-03-07 12:13 UTC, a364176773 commented on server/src/main/java/io/seata/server/coordinator/DefaultCore.java
> +        if (globalSession == null ||
tm端超时判断,不是tc端超时判断,这里进行判断的意义是?提前tm端超时,可以减少tmrpc的消耗,都到server端了没什么必要在判断了

2022-03-07 12:13 UTC, a364176773 commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +                    if (isTimeout(txInfo.getTimeOut(), beginTime)) {
在commitTransaction里进行判断,如果超时直接抛出throw new TransactionalExecutor.ExecutionException,code是timeoutrollback

2022-04-18 12:17 UTC, Bughue commented on spring/src/main/java/io/seata/spring/annotation/AspectTransactional.java
> +    int lossTime = 0;
这个默认值是不是该给一个大于零的数？

2022-04-18 12:17 UTC, Bughue commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactional.java
> +    int lossTime() default  0;
是否在这里给个大于0的数？

2022-04-18 12:17 UTC, Bughue commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +                    TransactionalExecutor.Code.TimeoutRollback);
是不是直接放try里面，然后throw new TransactionException(TransactionExceptionCode.GlobalTransactionNotActive);这样好点

2022-04-18 13:03 UTC, miaoxueyu commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +                    TransactionalExecutor.Code.TimeoutRollback);
这里主要是TransactionalExecutor.Code不同，catch块中侧重是commit failure，感觉commit失败和超时了压根不需要去commit还是不一样的

2022-04-18 13:05 UTC, miaoxueyu commented on spring/src/main/java/io/seata/spring/annotation/AspectTransactional.java
> +    int lossTime = 0;
我本来想的是默认没有，如果需要可以自己手动配置。给个默认值也是个不错的主意哦，有点拿不定给多少，可以一起讨论讨论哦

2022-04-18 13:05 UTC, miaoxueyu commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactional.java
> +    int lossTime() default  0;
同上

2022-07-05 03:45 UTC, a364176773 approved these changes
tc端的超时也要加上去

2022-07-05 03:45 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/AspectTransactional.java
> +    int lossTime = 0;
这应该是个float，0.5 ，1.5都是有可能的，而且要有配置项给用户去配置，默认值我觉得可以算个1ms

2022-07-05 03:47 UTC, a364176773 commented
点错了给了票，tc端的commit要做下超时判断，那个容错自要有全局配置和局部配置的功能，然后默认应该是有个1s

2022-07-05 03:48 UTC, a364176773 requested changes
点错了给了票，tc端的commit要做下超时判断，那个容错自要有全局配置和局部配置的功能，然后默认应该是有个1s，标题要规范起来，内容也不只是要做tm端

2022-07-14 13:38 UTC, a364176773 commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +                        rollbackTransaction(tx, e.getCause());
个人觉得直接把status响应出去就好了,tc端会异步回滚的,话说为什么要加个TimeoutRollback,而不用TimeoutRollbacking这个已有的status?

2022-07-14 13:38 UTC, a364176773 commented on tm/src/test/java/io/seata/tm/api/DefaultFailureHandlerImplTest.java
> +import io.netty.util.HashedWheelTimer;
无改动回滚

2022-07-14 13:38 UTC, a364176773 commented on tm/src/test/java/io/seata/tm/api/TransactionTemplateTest.java
> +
无改动回滚

2022-07-14 13:38 UTC, a364176773 commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +        final long lossTimeOfMicros = (long) txInfo.getLossTime() * conversionRate;
先当前时间戳减去begin时间戳,再直接比对loss是不是更简单点?

2022-07-16 02:50 UTC, miaoxueyu commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +                        rollbackTransaction(tx, e.getCause());
TC回滚的是我想错了，我写这个的时候想的是提交出错了岂不是要等到全局事务超时TC才会异步回滚，会不会等太久了，现在一看，这不就是事务超时才会执行这里嘛。不过如果在commit中出现了未知错误，那回滚要依赖TC的超时回滚会不会有点久了

2022-07-16 02:52 UTC, miaoxueyu commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +                        rollbackTransaction(tx, e.getCause());
话说TimeoutRollbacking是io.seata.core.model.GlobalStatus枚举里的，但是这里要的是TransactionalExecutor.Code呀

2022-07-16 03:01 UTC, miaoxueyu commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +        final long lossTimeOfMicros = (long) txInfo.getLossTime() * conversionRate;
这里的逻辑跟你想的是差不多的，是（当前时间  -  begin时间戳  - loss) > timeOut
因为loss是float类型的毫秒，所以都需要转为微妙去计算,显得有点麻烦

2022-07-16 03:01 UTC, miaoxueyu commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +        final long lossTimeOfMicros = (long) txInfo.getLossTime() * conversionRate;
已改

2022-07-16 11:33 UTC, a364176773 commented on core/src/main/java/io/seata/core/exception/TransactionExceptionCode.java
> +    GlobalTransactionTimeOut
这个用处是在哪?

2022-07-16 11:33 UTC, a364176773 commented on tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
> +    public long getCreateTimeOfNano() {
createTime和createTimeOfNano留一个可以吗?

2022-07-17 16:08 UTC, a364176773 approved these changes
LGTM

2022-08-30 03:28 UTC, slievrly commented on tm/src/main/java/io/seata/tm/api/DefaultFailureHandlerImpl.java
> +    public void onTimeOutRollback(GlobalTransaction tx, Throwable originalException) {
notice upper and lower case

2022-08-30 03:30 UTC, slievrly commented on test/src/test/java/io/seata/saga/engine/mock/MockGlobalTransaction.java
> +        return 0;
why always return 0?

2022-08-30 03:32 UTC, slievrly commented on tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
> +    public long getBeginTime() {
`createTime` is preferred on the client side and use `beginTime` on server side.

2022-08-30 03:48 UTC, slievrly commented on server/src/main/java/io/seata/server/coordinator/DefaultCore.java
> +            return GlobalStatus.TimeoutRollbacking;
add some log

2022-08-30 03:52 UTC, slievrly commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +        if (isTimeout(tx.getCreateTime(), txInfo)) {
why not send GlobalRollback directly?

2022-09-05 01:45 UTC, a364176773 commented on tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
> +        if (Objects.equals(tx.getLocalStatus(), GlobalStatus.TimeoutRollbacking)) {
加一个timeoutrollbacked，比如新老版本使用，client1.6 server1.5.2 这样server是没有自检timeout的导致可能请求过去响应是timeoutrollbacked或timeoutrollbacking

2022-09-06 08:00 UTC, Bughue reviewed
LGTM

2022-09-20 08:43 UTC, a364176773 commented
@slievrly PTAL

2022-09-21 03:49 UTC, slievrly approved these changes
LGTM

2022-09-21 03:54 UTC, slievrly commented
TODO: direct use of ` TransactionManager.commit ()`  whether do check is timeout.

2022-09-21 04:10 UTC, merged

2024-11-23 08:28 UTC, luky116 commented
seata-go: https://github.com/apache/incubator-seata-go/issues/698