seata客户端和服务端采用nacos为注册中心时，客户端导致订阅seata-server导致应用名称unknown.
seata/seata pull request #4448
Opened 2022-03-08 07:56 UTC by hadoop835

seata客户端和服务端采用nacos为注册中心时，客户端导致订阅seata-server导致应用名称unknown.
<img width="797" alt="1646721213617_1DA5E72A-349A-45d3-8025-434339207EC0" src="https://user-images.githubusercontent.com/8055054/157191810-a886248f-e97d-4436-8c3b-e18d7139fbe6.png">

2022-03-08 13:23 UTC, a364176773 requested changes
script文件夹中client中的相关配置补充一下

2022-03-08 13:24 UTC, a364176773 commented
标题英文,optimize: 开头

2022-12-12 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/seata/seata?pullRequest=4448) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/seata/seata?pullRequest=4448) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: chenzhh<br/>:x: a364176773<br/>:x: hadoop835<br/><hr/>**chenzhh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/seata/seata?pullRequest=4448) it.</sub>

2022-12-12 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/seata/seata?pullRequest=4448) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/seata/seata?pullRequest=4448) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: chenzhh<br/>:x: hadoop835<br/>:x: a364176773<br/><hr/>**chenzhh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/seata/seata?pullRequest=4448) it.</sub>

2023-08-14 10:33 UTC, a364176773 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryNacosProperties.java
> +    private String clientApplication = "";
未涉及的逻辑和代码不要去改动

2023-08-14 10:34 UTC, a364176773 reviewed
yml中的使用方式需要补充进去

2023-08-15 05:56 UTC, hadoop835 commented
> yml中的使用方式需要补充进去

加在哪里呢

2023-08-15 06:40 UTC, closed without merging

2023-08-15 07:02 UTC, a364176773 commented
> > yml中的使用方式需要补充进去
> 
> 加在哪里呢

server里的resources里的application.example.yml