optimize: modify acquisition configuration method
seata/seata pull request #4469
Opened 2022-03-14 13:54 UTC by lvekee

### Ⅰ. Describe what this PR did
modify acquisition configuration method

2022-03-15 02:40 UTC, lightClouds917 approved these changes
LGTM

2022-03-15 15:03 UTC, a364176773 requested changes

2022-03-19 04:45 UTC, a364176773 approved these changes
LGTM

2022-03-19 04:45 UTC, merged

2022-03-19 16:43 UTC, slievrly reviewed
LGTM