optimizesupport where method condition 4565
seata/seata pull request #4567
Opened 2022-04-24 09:45 UTC by doubleDimple

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-05-03 15:56 UTC, caohdgege approved these changes
LGTM，补充一下md文件

2022-05-06 14:55 UTC, a364176773 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +    public static final List<String> SUPPORT_SQL_METHODS = new ArrayList<>();
new TreeSet<>(String.CASE_INSENSITIVE_ORDER);
且最好为单例,不要public直接给出去,而是给一个单例instance出去,再通过掉单例的add接口去添加支持的method

2022-05-06 15:53 UTC, doubleDimple commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +    public static final List<String> SUPPORT_SQL_METHODS = new ArrayList<>();
get

2022-05-07 11:37 UTC, a364176773 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +        add();
这不太对呀,FIND_IN_SET写在staic{}中,下面的add做成public ,其它地方可以掉SupportSqlWhereMethod.getInstance).add(method)

2022-05-08 05:41 UTC, a364176773 requested changes

2022-05-08 05:41 UTC, a364176773 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +    private static final Set<String> SUPPORT_SQL_METHODS = new TreeSet<>(String.CASE_INSENSITIVE_ORDER);
static 去掉,通过调用getInstance拿到实例后进行add添加

2022-05-08 05:41 UTC, a364176773 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +    private static void add() {
public void add(String method)

2022-05-08 14:21 UTC, doubleDimple commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +        add();
get

2022-05-08 14:21 UTC, doubleDimple commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +    private static final Set<String> SUPPORT_SQL_METHODS = new TreeSet<>(String.CASE_INSENSITIVE_ORDER);
get

2022-05-08 14:21 UTC, doubleDimple commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +    private static void add() {
get

2022-05-09 05:08 UTC, a364176773 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +        if (supportMethodNames.contains(methodName)) {
return supportMethodNames.contains(methodName)

2022-05-09 05:09 UTC, a364176773 commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +        getInstance().add("FIND_IN_SET");
写在SupportSqlWhereMethod 构造函数里比较好 public SupportSqlWhereMethod(){
add("FIND_IN_SET");
}

2022-05-09 12:47 UTC, doubleDimple commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +        getInstance().add("FIND_IN_SET");
get

2022-05-09 12:47 UTC, doubleDimple commented on sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SupportSqlWhereMethod.java
> +        if (supportMethodNames.contains(methodName)) {
get

2022-05-10 08:49 UTC, pengten commented
好多非必要的代码格式化 orz

2022-05-10 08:50 UTC, pengten commented on changes/en-us/2.0.0.md
好多非必要的代码格式化 orz

2022-05-17 14:03 UTC, a364176773 approved these changes
LGTM

2022-05-17 14:03 UTC, merged