bugfix:auto degrade unable dynamic configure
seata/seata pull request #4590
Opened 2022-05-07 09:31 UTC by pengten

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
自动降级如果一开始为false，运行中也无法通过修改配置来动态开启

### Ⅱ. Does this pull request fix one issue?

fixes #4491 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-05-09 02:45 UTC, a364176773 requested changes

2022-05-09 02:45 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +        if (executor != null && !executor.isShutdown()) {
不加锁弄个atomicboolean来处理吧

2022-05-09 02:45 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +        if (executor != null && !executor.isShutdown()) {
同上

2022-05-09 02:45 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +            executor.shutdownNow();
shutdown就好了，优雅点

2022-05-10 10:12 UTC, pengten commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +        if (executor != null && !executor.isShutdown()) {
改了一版本，虽然没锁了，但是感觉更复杂了

2022-05-17 14:06 UTC, a364176773 requested changes

2022-05-17 14:06 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +        while (!autoDegradeChange.compareAndSet(false, true)) {
为什么这里要while+sleep?
如果失败了不代表线程本身就没开启嘛,直接return就行了

2022-05-17 14:06 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +        while (!autoDegradeChange.compareAndSet(false, true)) {
同理上面,如果失败了,说明已经start了,直接return即可

2022-05-22 12:41 UTC, a364176773 requested changes

2022-05-22 12:41 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +            autoDegradeChange.set(false);
都compareAndSet了,为何还要set?

2022-05-22 12:41 UTC, a364176773 commented on spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
> +            autoDegradeChange.set(false);
同下

2022-05-23 10:34 UTC, a364176773 approved these changes
LGTM pr登记一下

2022-08-20 15:50 UTC, slievrly approved these changes
LGTM

2022-08-21 04:48 UTC, merged