Sher branch
seata/seata pull request #4783
Opened 2022-07-17 03:29 UTC by SherZhou

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
optimise: Add some controllers to implement inner http request from console to server.
Delete the dependency of console in server module  and add some necessary classes at the same time.

### Ⅱ. Does this pull request fix one issue?

fixes #4782

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-07-18 01:35 UTC, lightClouds917 commented
根据build失败的detail，代码格式全局调整下，比如无用的import，括号前少空格等。

2022-08-02 01:42 UTC, lightClouds917 commented
下载一个阿里巴巴代码扫描插件，先根据插件扫描结果，尽可能的把自己的代码写规范。seata社区一直以来对编码要求比较高，现在用户基数非常庞大，编码风格和细节上，我们希望能够是高质量的，精益求精的，注意细节的，风格统一的。
后面的每一个review code的人，都还会看这些细节，优化一下。

2022-08-02 01:55 UTC, lightClouds917 requested changes

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/config/RestClientConfig.java
> + * @date: 2022/6/30
全局问题：日期不要，但是需要有类作用的描述

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/config/RestClientConfig.java
> +
没必要的空行都删除掉

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +    //address of server module
规范注释的用法。//  和/**   */的区别

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +
对外的接口？接口声明呢

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +            LOGGER.error("Server request error:", e);
err里可以添加上自己的特有信息，帮助用户理解，不要简单的打印系统错误信息。

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +    // generate server http request url
看起来是一个公共逻辑。抽取成静态方法/工具方法。全局检查此类问题。

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +    private HttpEntity<String> getHttpEntity(HttpServletRequest request) {
同上，抽取。以及规范注释/***/

2022-08-02 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/GlobalLockServerController.java
> +        String url = "http://" + address + ":" + port + "/server" + requesturl + "?" + queryString;
stringbuilder拼接字符串

2022-08-17 09:08 UTC, SherZhou commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +@RequestMapping("/console/branchSession")
done

2022-08-17 09:57 UTC, SherZhou commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +    //address of server module
done

2022-08-17 09:58 UTC, SherZhou commented on server/src/main/java/io/seata/server/console/filter/JwtAuthenticationTokenFilter.java
> +=======
done

2022-08-17 09:58 UTC, SherZhou commented on console/src/main/resources/application.yml
> +seata:
done

2022-08-17 09:58 UTC, SherZhou commented on console/src/main/java/io/seata/console/config/RestClientConfig.java
> + * @date: 2022/6/30
done

2022-08-17 09:59 UTC, SherZhou commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +
done

2022-08-17 10:00 UTC, SherZhou commented on console/src/main/java/io/seata/console/config/RestClientConfig.java
> +
done

2022-08-17 10:00 UTC, SherZhou commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +            LOGGER.error("Server request error:", e);
done

2022-08-17 10:01 UTC, SherZhou commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +    // generate server http request url
done

2022-08-17 10:01 UTC, SherZhou commented on console/src/main/java/io/seata/console/controller/BranchSessionServerController.java
> +    private HttpEntity<String> getHttpEntity(HttpServletRequest request) {
done

2022-08-17 11:47 UTC, SherZhou commented on server/src/main/java/io/seata/server/console/filter/JwtAuthenticationTokenFilter.java
> +=======
done

2022-09-19 01:55 UTC, lightClouds917 requested changes

2022-09-19 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/GlobalLockServerController.java
> +    @Autowired
GlobalLockServerController.class，日志类错了

2022-09-19 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/utils/UrlUtils.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(GlobalSessionServerController.class);
not GlobalSessionServerController.class

2022-09-19 01:55 UTC, lightClouds917 commented on server/pom.xml
> +<!--            <artifactId>seata-console</artifactId>-->
不用就直接删除掉

2022-09-19 01:55 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/filter/JwtAuthenticationTokenFilter.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(JwtTokenUtils.class);
JwtAuthenticationTokenFilter.class

2022-09-19 01:55 UTC, lightClouds917 commented on server/src/main/java/io/seata/server/console/filter/WebSecurityConfig.java
> +<<<<<<< HEAD
无用字符串删除了，这看起来是合并冲突导致的

2022-09-19 01:55 UTC, lightClouds917 commented on console/src/main/java/io/seata/console/controller/GlobalSessionServerController.java
> +    PageResult<GlobalSessionVO> queryByXid(GlobalSessionParam param) {
queryByXid？query or queryByParam？

2022-09-26 02:38 UTC, lightClouds917 approved these changes

2022-10-26 02:46 UTC, merged