on the Seata client 死的
seata/seata pull request #4878
Opened 2022-08-22 11:56 UTC by robynron

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-08-28 04:39 UTC, lvekee requested changes

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/TMMeterIdConstants.java
> +package io.seata.metrics;
Copyright 加一下

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/service/MetricsPublisher.java
> +package io.seata.metrics.service;
Copyright加一下

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/service/MetricsPublisher.java
> +import io.seata.core.context.RootContext;
无用包不要导入

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/service/MetricsSubscriber.java
> +import static io.seata.metrics.IdConstants.*;
不要*号导入

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/service/MetricsSubscriber.java
> +import io.seata.metrics.IdConstants;
无用包不要导入

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/service/MetricsSubscriber.java
> +        }else if (MetricsManager.get().getRole().equals(MetricsManager.get().ROLE_VALUE_CLIENT)) {
p3c格式化下代码

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/service/MetricsSubscriber.java
> +            if (consumers.containsKey(event.getMetricEvent())){
格式化下代码 少空格

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/RMMeterIdConstants.java
> +
CopyRight加一下

2022-08-28 04:39 UTC, lvekee commented on metrics/seata-metrics-service/src/main/java/io/seata/metrics/TCMeterIdConstants.java
> +import io.seata.metrics.IdConstants;
导包改一下

2022-08-28 05:27 UTC, lvekee requested changes

2022-08-28 05:27 UTC, lvekee commented on rm/src/main/java/io/seata/rm/DefaultResourceManager.java
> +import io.seata.metrics.service.MetricsPublisher;
去掉无用导包

2022-08-28 05:27 UTC, lvekee commented on rm/src/main/java/io/seata/rm/DefaultResourceManager.java
> +
去掉空行

2022-12-12 13:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/seata/seata?pullRequest=4878) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/seata/seata?pullRequest=4878) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/seata/seata?pullRequest=4878) it.</sub>

2023-05-16 07:56 UTC, Bughue commented
是不是要关联下  https://github.com/seata/seata/tree/develop/metrics#readme

2023-11-28 05:50 UTC, funky-eyes commented
Due to code conflicts and age, if you are still interested in participating in the community, please resubmit this pr to the 2.x branch after resolving the conflict.
由于代码冲突以及年代久远，如果你还有兴趣参与到社区，请解决完冲突后重新请提交这份pr至2.x分支中

2023-11-28 05:50 UTC, closed without merging

2023-11-28 06:07 UTC, robynron commented
好的，我后面基于2.x分支重新弄一下