fix(sec): upgrade com.h2database:h2 to 2.1.210
seata/seata pull request #4979
Opened 2022-10-08 06:33 UTC by ren-jq101

### What happened？
There are 4 security vulnerabilities found in com.h2database:h2 1.4.181
- [CVE-2018-14335](https://www.oscs1024.com/hd/CVE-2018-14335)
- [CVE-2021-42392](https://www.oscs1024.com/hd/CVE-2021-42392)
- [CVE-2022-23221](https://www.oscs1024.com/hd/CVE-2022-23221)
- [MPS-2022-52737](https://www.oscs1024.com/hd/MPS-2022-52737)

### What did I do？
Upgrade com.h2database:h2 from 1.4.181 to 2.1.210 for vulnerability fix

### What did you expect to happen？
Ideally, no insecure libs should be used.

### The specification of the pull request
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

2022-10-08 06:41 UTC, a364176773 requested changes

2022-10-08 06:41 UTC, a364176773 commented on dependencies/pom.xml
> +  --><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4
don't change

2022-10-08 06:41 UTC, a364176773 commented on dependencies/pom.xml
> +</project>
don't change

2022-10-09 05:07 UTC, slievrly commented
@ren-jq101 Do not make any changes other than the version you changed.

2022-10-09 06:29 UTC, ren-jq101 commented
This pr has been moved to #4980

2022-10-09 06:29 UTC, closed without merging