Hotfix field distinct
seata/seata pull request #4985
Opened 2022-10-10 07:42 UTC by whxxxxx

- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
fix undo_log id repeat

### Ⅱ. Does this pull request fix one issue?
https://github.com/seata/seata/issues/4949

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-10-10 07:46 UTC, a364176773 requested changes

2022-10-10 07:49 UTC, whxxxxx commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
> +                org.apache.commons.lang.StringUtils.replace(insertColumn, "`", "");
> Why not handle it in SQLInsertRecognizer#getInsertColumns

因为我想的是SQLInsertRecognizer#getInsertColumns可以获取真实sql中所写的字段，所以没有通过修改这个方法来处理

2022-10-10 09:05 UTC, a364176773 commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
> +                org.apache.commons.lang.StringUtils.replace(insertColumn, "`", "");
> > Why not handle it in SQLInsertRecognizer#getInsertColumns
> 
> 因为我想的是SQLInsertRecognizer#getInsertColumns可以获取真实sql中所写的字段，所以没有通过修改这个方法来处理

Maybe you can add a new method

2022-10-10 11:40 UTC, whxxxxx commented on rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
> +                org.apache.commons.lang.StringUtils.replace(insertColumn, "`", "");
> > > Why not handle it in SQLInsertRecognizer#getInsertColumns
> > 
> > 
> > 因为我想的是SQLInsertRecognizer#getInsertColumns可以获取真实sql中所写的字段，所以没有通过修改这个方法来处理
> 
> Maybe you can add a new method

想过，但是发现修改的点可能会更多，所以还是选择了这种方式

2022-10-11 01:42 UTC, a364176773 commented on sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/SQLInsertRecognizer.java
> +            org.apache.commons.lang.StringUtils.replace(insertColumn, "`", "");
Use methods that already exist in ColumnUtils

2022-10-12 06:15 UTC, a364176773 approved these changes
LGTM

2022-10-12 09:47 UTC, slievrly approved these changes
LGTM

2022-10-12 10:10 UTC, merged

2024-11-23 08:53 UTC, luky116 commented
seata-go: https://github.com/apache/incubator-seata/pull/4985